/********************************************************************************
** Form generated from reading UI file 'demo.ui'
**
** Created by: Qt User Interface Compiler version 5.12.10
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DEMO_H
#define UI_DEMO_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>
#include "mylabel.h"

QT_BEGIN_NAMESPACE

class Ui_Demo
{
public:
    QWidget *CENTRAL;
    QGroupBox *IMG_GRAB_STATIC;
    QRadioButton *CONTINUOUS_RADIO;
    QRadioButton *TRIGGER_RADIO;
    QCheckBox *SOFTWARE_CHECK;
    QPushButton *START_GRABBING_BUTTON;
    QPushButton *STOP_GRABBING_BUTTON;
    QPushButton *SOFTWARE_TRIGGER_BUTTON;
    QGroupBox *IMG_SAVE_STATIC;
    QCheckBox *CUSTOM_FILENAME_CHECK;
    QLabel *FILENAME_STATIC;
    QPushButton *SAVE_BMP_BUTTON;
    QLineEdit *FILE_PATH_EDIT;
    QToolButton *FILE_PATH_BROWSE;
    QPushButton *SAVE_AVI_BUTTON;
    QPushButton *SAVE_JPG_BUTTON;
    QPushButton *SAVE_RESULT_BUTTON;
    QGroupBox *PARAMS_STATIC;
    QLabel *GAIN_STATIC;
    QLineEdit *GAIN_EDIT;
    QSlider *GAIN_SLIDER;
    QPushButton *SET_PARAMS_BUTTON;
    QLineEdit *CCD_FREQ_EDIT;
    QLabel *CCD_FREQ;
    QLabel *CCD_FREQ_UNIT;
    QLabel *TIME_EXPOSURE;
    QGroupBox *OPERATION_STATIC;
    QCheckBox *IMG_SMOOTH_CHECK;
    QCheckBox *IMG_ENHANCE_CHECK;
    QComboBox *SMOOTH_OPTIONS;
    QComboBox *ENHANCE_OPTIONS;
    QCheckBox *SP_CHECK;
    QComboBox *SP_OPTIONS;
    QCheckBox *FRAME_AVG_CHECK;
    QComboBox *FRAME_AVG_OPTIONS;
    MyLabel *SOURCE_DISPLAY;
    QPushButton *CLS_BUTTON;
    QTabWidget *INITIALIZATION;
    QWidget *DEVICE;
    QPushButton *SHUTDOWN_BUTTON;
    QPushButton *START_BUTTON;
    QPushButton *ENUM_BUTTON;
    QWidget *COM;
    QLabel *TCU_COM;
    QLabel *RANGE_COM;
    QLabel *FOCUS_COM;
    QLabel *THERMO_COM;
    QLineEdit *TCU_COM_EDIT;
    QLineEdit *RANGE_COM_EDIT;
    QLineEdit *FOCUS_COM_EDIT;
    QLineEdit *THERMO_COM_EDIT;
    QGroupBox *TCU_STATIC;
    QLineEdit *FREQ_EDIT;
    QLabel *FREQ;
    QLabel *FREQ_UNIT;
    QLabel *LASER_WIDTH;
    QLineEdit *LASER_WIDTH_EDIT_U;
    QLineEdit *LASER_WIDTH_EDIT_N;
    QLabel *LASER_WIDTH_U_UNIT;
    QLabel *LASER_WIDTH_N_UNIT;
    QLabel *TCU_A;
    QLabel *TCU_B;
    QLabel *DELAY_A_UNIT_N;
    QLineEdit *DELAY_A_EDIT_N;
    QLabel *DELAY_A_UNIT_U;
    QLabel *DELAY_A;
    QLineEdit *DELAY_A_EDIT_U;
    QLabel *DELAY_B;
    QLineEdit *DELAY_B_EDIT_U;
    QLabel *DELAY_B_UNIT_U;
    QLabel *DELAY_B_UNIT_N;
    QLineEdit *DELAY_B_EDIT_N;
    QLabel *GATE_WIDTH_A;
    QLineEdit *GATE_WIDTH_B_EDIT_U;
    QLineEdit *GATE_WIDTH_A_EDIT_U;
    QLabel *GATE_WIDTH_A_UNIT_U;
    QLineEdit *GATE_WIDTH_B_EDIT_N;
    QLabel *GATE_WIDTH_A_UNIT_N;
    QLabel *GATE_WIDTH_B;
    QLabel *GATE_WIDTH_B_UNIT_N;
    QLineEdit *GATE_WIDTH_A_EDIT_N;
    QLabel *GATE_WIDTH_B_UNIT_U;
    QGroupBox *LENS_STATIC;
    QLabel *ZOOM;
    QLabel *FOCUS;
    QPushButton *ZOOM_IN_BTN;
    QPushButton *FOCUS_NEAR_BTN;
    QPushButton *ZOOM_OUT_BTN;
    QPushButton *FOCUS_FAR_BTN;
    QLineEdit *ZOOM_EDIT;
    QPushButton *GET_ZOOM_BTN;
    QPushButton *SET_ZOOM_BTN;
    QPushButton *GET_FOCUS_BTN;
    QLineEdit *FOCUS_EDIT;
    QPushButton *SET_FOCUS_BTN;
    QSlider *FOCUS_SPEED_SLIDER;
    QLineEdit *FOCUS_SPEED_EDIT;
    QTextEdit *DATA_EXCHANGE;
    QPushButton *DIST_BTN;
    QLabel *DISTANCE;
    QLabel *GATE_WIDTH;
    QLabel *ESTIMATED_2;
    QPushButton *SCAN_BUTTON;
    QPushButton *CONTINUE_SCAN_BUTTON;
    QPushButton *RESTART_SCAN_BUTTON;
    QLabel *EST_DIST;
    QLabel *ESTIMATED;
    QGroupBox *CTRL_STATIC;
    QLabel *DELAY_DIST;
    QLabel *MCP;
    QSlider *MCP_SLIDER;
    QSlider *DELAY_SLIDER;
    QLabel *LOGO1;
    QLabel *DUTY_UNIT;
    QPushButton *GET_PARAMS_BUTTON;
    QLabel *DUTY;
    QLineEdit *DUTY_EDIT;
    QLabel *NAME;
    QLabel *LOGO2;

    void setupUi(QMainWindow *Demo)
    {
        if (Demo->objectName().isEmpty())
            Demo->setObjectName(QString::fromUtf8("Demo"));
        Demo->resize(1133, 665);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(Demo->sizePolicy().hasHeightForWidth());
        Demo->setSizePolicy(sizePolicy);
        Demo->setMinimumSize(QSize(1133, 665));
        QFont font;
        font.setFamily(QString::fromUtf8("Consolas"));
        font.setPointSize(8);
        Demo->setFont(font);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/logo/1.png"), QSize(), QIcon::Normal, QIcon::Off);
        Demo->setWindowIcon(icon);
        Demo->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        CENTRAL = new QWidget(Demo);
        CENTRAL->setObjectName(QString::fromUtf8("CENTRAL"));
        IMG_GRAB_STATIC = new QGroupBox(CENTRAL);
        IMG_GRAB_STATIC->setObjectName(QString::fromUtf8("IMG_GRAB_STATIC"));
        IMG_GRAB_STATIC->setGeometry(QRect(20, 130, 191, 91));
        IMG_GRAB_STATIC->setFont(font);
        CONTINUOUS_RADIO = new QRadioButton(IMG_GRAB_STATIC);
        CONTINUOUS_RADIO->setObjectName(QString::fromUtf8("CONTINUOUS_RADIO"));
        CONTINUOUS_RADIO->setGeometry(QRect(10, 25, 85, 18));
        TRIGGER_RADIO = new QRadioButton(IMG_GRAB_STATIC);
        TRIGGER_RADIO->setObjectName(QString::fromUtf8("TRIGGER_RADIO"));
        TRIGGER_RADIO->setGeometry(QRect(10, 45, 67, 18));
        SOFTWARE_CHECK = new QCheckBox(IMG_GRAB_STATIC);
        SOFTWARE_CHECK->setObjectName(QString::fromUtf8("SOFTWARE_CHECK"));
        SOFTWARE_CHECK->setGeometry(QRect(20, 65, 91, 18));
        START_GRABBING_BUTTON = new QPushButton(IMG_GRAB_STATIC);
        START_GRABBING_BUTTON->setObjectName(QString::fromUtf8("START_GRABBING_BUTTON"));
        START_GRABBING_BUTTON->setGeometry(QRect(120, 25, 61, 20));
        STOP_GRABBING_BUTTON = new QPushButton(IMG_GRAB_STATIC);
        STOP_GRABBING_BUTTON->setObjectName(QString::fromUtf8("STOP_GRABBING_BUTTON"));
        STOP_GRABBING_BUTTON->setGeometry(QRect(120, 45, 61, 20));
        SOFTWARE_TRIGGER_BUTTON = new QPushButton(IMG_GRAB_STATIC);
        SOFTWARE_TRIGGER_BUTTON->setObjectName(QString::fromUtf8("SOFTWARE_TRIGGER_BUTTON"));
        SOFTWARE_TRIGGER_BUTTON->setGeometry(QRect(130, 65, 41, 20));
        IMG_SAVE_STATIC = new QGroupBox(CENTRAL);
        IMG_SAVE_STATIC->setObjectName(QString::fromUtf8("IMG_SAVE_STATIC"));
        IMG_SAVE_STATIC->setGeometry(QRect(20, 230, 191, 101));
        IMG_SAVE_STATIC->setFont(font);
        CUSTOM_FILENAME_CHECK = new QCheckBox(IMG_SAVE_STATIC);
        CUSTOM_FILENAME_CHECK->setObjectName(QString::fromUtf8("CUSTOM_FILENAME_CHECK"));
        CUSTOM_FILENAME_CHECK->setGeometry(QRect(70, 20, 121, 18));
        FILENAME_STATIC = new QLabel(IMG_SAVE_STATIC);
        FILENAME_STATIC->setObjectName(QString::fromUtf8("FILENAME_STATIC"));
        FILENAME_STATIC->setGeometry(QRect(10, 20, 54, 12));
        SAVE_BMP_BUTTON = new QPushButton(IMG_SAVE_STATIC);
        SAVE_BMP_BUTTON->setObjectName(QString::fromUtf8("SAVE_BMP_BUTTON"));
        SAVE_BMP_BUTTON->setGeometry(QRect(10, 70, 40, 20));
        FILE_PATH_EDIT = new QLineEdit(IMG_SAVE_STATIC);
        FILE_PATH_EDIT->setObjectName(QString::fromUtf8("FILE_PATH_EDIT"));
        FILE_PATH_EDIT->setGeometry(QRect(10, 40, 151, 20));
        FILE_PATH_BROWSE = new QToolButton(IMG_SAVE_STATIC);
        FILE_PATH_BROWSE->setObjectName(QString::fromUtf8("FILE_PATH_BROWSE"));
        FILE_PATH_BROWSE->setGeometry(QRect(161, 40, 20, 20));
        SAVE_AVI_BUTTON = new QPushButton(IMG_SAVE_STATIC);
        SAVE_AVI_BUTTON->setObjectName(QString::fromUtf8("SAVE_AVI_BUTTON"));
        SAVE_AVI_BUTTON->setGeometry(QRect(130, 70, 50, 20));
        SAVE_JPG_BUTTON = new QPushButton(IMG_SAVE_STATIC);
        SAVE_JPG_BUTTON->setObjectName(QString::fromUtf8("SAVE_JPG_BUTTON"));
        SAVE_JPG_BUTTON->setGeometry(QRect(90, 70, 40, 20));
        SAVE_RESULT_BUTTON = new QPushButton(IMG_SAVE_STATIC);
        SAVE_RESULT_BUTTON->setObjectName(QString::fromUtf8("SAVE_RESULT_BUTTON"));
        SAVE_RESULT_BUTTON->setGeometry(QRect(50, 70, 40, 20));
        PARAMS_STATIC = new QGroupBox(CENTRAL);
        PARAMS_STATIC->setObjectName(QString::fromUtf8("PARAMS_STATIC"));
        PARAMS_STATIC->setGeometry(QRect(20, 340, 191, 121));
        PARAMS_STATIC->setFont(font);
        GAIN_STATIC = new QLabel(PARAMS_STATIC);
        GAIN_STATIC->setObjectName(QString::fromUtf8("GAIN_STATIC"));
        GAIN_STATIC->setGeometry(QRect(20, 72, 24, 13));
        GAIN_EDIT = new QLineEdit(PARAMS_STATIC);
        GAIN_EDIT->setObjectName(QString::fromUtf8("GAIN_EDIT"));
        GAIN_EDIT->setGeometry(QRect(130, 69, 51, 20));
        GAIN_SLIDER = new QSlider(PARAMS_STATIC);
        GAIN_SLIDER->setObjectName(QString::fromUtf8("GAIN_SLIDER"));
        GAIN_SLIDER->setGeometry(QRect(20, 90, 151, 20));
        GAIN_SLIDER->setOrientation(Qt::Horizontal);
        SET_PARAMS_BUTTON = new QPushButton(PARAMS_STATIC);
        SET_PARAMS_BUTTON->setObjectName(QString::fromUtf8("SET_PARAMS_BUTTON"));
        SET_PARAMS_BUTTON->setGeometry(QRect(119, 37, 61, 20));
        CCD_FREQ_EDIT = new QLineEdit(PARAMS_STATIC);
        CCD_FREQ_EDIT->setObjectName(QString::fromUtf8("CCD_FREQ_EDIT"));
        CCD_FREQ_EDIT->setGeometry(QRect(16, 37, 61, 20));
        CCD_FREQ = new QLabel(PARAMS_STATIC);
        CCD_FREQ->setObjectName(QString::fromUtf8("CCD_FREQ"));
        CCD_FREQ->setGeometry(QRect(16, 23, 55, 13));
        CCD_FREQ_UNIT = new QLabel(PARAMS_STATIC);
        CCD_FREQ_UNIT->setObjectName(QString::fromUtf8("CCD_FREQ_UNIT"));
        CCD_FREQ_UNIT->setGeometry(QRect(80, 40, 12, 13));
        TIME_EXPOSURE = new QLabel(PARAMS_STATIC);
        TIME_EXPOSURE->setObjectName(QString::fromUtf8("TIME_EXPOSURE"));
        TIME_EXPOSURE->setGeometry(QRect(110, 0, 54, 12));
        OPERATION_STATIC = new QGroupBox(CENTRAL);
        OPERATION_STATIC->setObjectName(QString::fromUtf8("OPERATION_STATIC"));
        OPERATION_STATIC->setGeometry(QRect(20, 470, 191, 111));
        OPERATION_STATIC->setFont(font);
        IMG_SMOOTH_CHECK = new QCheckBox(OPERATION_STATIC);
        IMG_SMOOTH_CHECK->setObjectName(QString::fromUtf8("IMG_SMOOTH_CHECK"));
        IMG_SMOOTH_CHECK->setGeometry(QRect(10, 20, 74, 19));
        IMG_ENHANCE_CHECK = new QCheckBox(OPERATION_STATIC);
        IMG_ENHANCE_CHECK->setObjectName(QString::fromUtf8("IMG_ENHANCE_CHECK"));
        IMG_ENHANCE_CHECK->setGeometry(QRect(10, 60, 67, 19));
        SMOOTH_OPTIONS = new QComboBox(OPERATION_STATIC);
        SMOOTH_OPTIONS->setObjectName(QString::fromUtf8("SMOOTH_OPTIONS"));
        SMOOTH_OPTIONS->setGeometry(QRect(90, 20, 91, 22));
        ENHANCE_OPTIONS = new QComboBox(OPERATION_STATIC);
        ENHANCE_OPTIONS->setObjectName(QString::fromUtf8("ENHANCE_OPTIONS"));
        ENHANCE_OPTIONS->setGeometry(QRect(90, 60, 91, 22));
        SP_CHECK = new QCheckBox(OPERATION_STATIC);
        SP_CHECK->setObjectName(QString::fromUtf8("SP_CHECK"));
        SP_CHECK->setGeometry(QRect(10, 80, 72, 19));
        SP_OPTIONS = new QComboBox(OPERATION_STATIC);
        SP_OPTIONS->setObjectName(QString::fromUtf8("SP_OPTIONS"));
        SP_OPTIONS->setGeometry(QRect(90, 80, 91, 22));
        FRAME_AVG_CHECK = new QCheckBox(OPERATION_STATIC);
        FRAME_AVG_CHECK->setObjectName(QString::fromUtf8("FRAME_AVG_CHECK"));
        FRAME_AVG_CHECK->setGeometry(QRect(10, 40, 80, 19));
        FRAME_AVG_OPTIONS = new QComboBox(OPERATION_STATIC);
        FRAME_AVG_OPTIONS->setObjectName(QString::fromUtf8("FRAME_AVG_OPTIONS"));
        FRAME_AVG_OPTIONS->setGeometry(QRect(90, 40, 91, 22));
        SOURCE_DISPLAY = new MyLabel(CENTRAL);
        SOURCE_DISPLAY->setObjectName(QString::fromUtf8("SOURCE_DISPLAY"));
        SOURCE_DISPLAY->setGeometry(QRect(230, 60, 640, 400));
        SOURCE_DISPLAY->setFrameShape(QFrame::Box);
        CLS_BUTTON = new QPushButton(CENTRAL);
        CLS_BUTTON->setObjectName(QString::fromUtf8("CLS_BUTTON"));
        CLS_BUTTON->setGeometry(QRect(230, 30, 31, 20));
        CLS_BUTTON->setFont(font);
        INITIALIZATION = new QTabWidget(CENTRAL);
        INITIALIZATION->setObjectName(QString::fromUtf8("INITIALIZATION"));
        INITIALIZATION->setGeometry(QRect(20, 20, 191, 101));
        DEVICE = new QWidget();
        DEVICE->setObjectName(QString::fromUtf8("DEVICE"));
        SHUTDOWN_BUTTON = new QPushButton(DEVICE);
        SHUTDOWN_BUTTON->setObjectName(QString::fromUtf8("SHUTDOWN_BUTTON"));
        SHUTDOWN_BUTTON->setGeometry(QRect(100, 40, 81, 20));
        START_BUTTON = new QPushButton(DEVICE);
        START_BUTTON->setObjectName(QString::fromUtf8("START_BUTTON"));
        START_BUTTON->setGeometry(QRect(10, 40, 81, 20));
        ENUM_BUTTON = new QPushButton(DEVICE);
        ENUM_BUTTON->setObjectName(QString::fromUtf8("ENUM_BUTTON"));
        ENUM_BUTTON->setGeometry(QRect(10, 10, 171, 20));
        INITIALIZATION->addTab(DEVICE, QString());
        COM = new QWidget();
        COM->setObjectName(QString::fromUtf8("COM"));
        TCU_COM = new QLabel(COM);
        TCU_COM->setObjectName(QString::fromUtf8("TCU_COM"));
        TCU_COM->setGeometry(QRect(10, 13, 18, 13));
        RANGE_COM = new QLabel(COM);
        RANGE_COM->setObjectName(QString::fromUtf8("RANGE_COM"));
        RANGE_COM->setGeometry(QRect(100, 13, 30, 13));
        FOCUS_COM = new QLabel(COM);
        FOCUS_COM->setObjectName(QString::fromUtf8("FOCUS_COM"));
        FOCUS_COM->setGeometry(QRect(10, 43, 30, 13));
        THERMO_COM = new QLabel(COM);
        THERMO_COM->setObjectName(QString::fromUtf8("THERMO_COM"));
        THERMO_COM->setGeometry(QRect(100, 43, 36, 13));
        TCU_COM_EDIT = new QLineEdit(COM);
        TCU_COM_EDIT->setObjectName(QString::fromUtf8("TCU_COM_EDIT"));
        TCU_COM_EDIT->setGeometry(QRect(45, 10, 31, 20));
        RANGE_COM_EDIT = new QLineEdit(COM);
        RANGE_COM_EDIT->setObjectName(QString::fromUtf8("RANGE_COM_EDIT"));
        RANGE_COM_EDIT->setGeometry(QRect(140, 10, 31, 20));
        FOCUS_COM_EDIT = new QLineEdit(COM);
        FOCUS_COM_EDIT->setObjectName(QString::fromUtf8("FOCUS_COM_EDIT"));
        FOCUS_COM_EDIT->setGeometry(QRect(45, 40, 31, 20));
        THERMO_COM_EDIT = new QLineEdit(COM);
        THERMO_COM_EDIT->setObjectName(QString::fromUtf8("THERMO_COM_EDIT"));
        THERMO_COM_EDIT->setGeometry(QRect(140, 40, 31, 20));
        INITIALIZATION->addTab(COM, QString());
        TCU_STATIC = new QGroupBox(CENTRAL);
        TCU_STATIC->setObjectName(QString::fromUtf8("TCU_STATIC"));
        TCU_STATIC->setGeometry(QRect(610, 370, 221, 261));
        FREQ_EDIT = new QLineEdit(TCU_STATIC);
        FREQ_EDIT->setObjectName(QString::fromUtf8("FREQ_EDIT"));
        FREQ_EDIT->setGeometry(QRect(20, 34, 61, 20));
        FREQ = new QLabel(TCU_STATIC);
        FREQ->setObjectName(QString::fromUtf8("FREQ"));
        FREQ->setGeometry(QRect(20, 20, 55, 13));
        FREQ_UNIT = new QLabel(TCU_STATIC);
        FREQ_UNIT->setObjectName(QString::fromUtf8("FREQ_UNIT"));
        FREQ_UNIT->setGeometry(QRect(84, 37, 18, 13));
        LASER_WIDTH = new QLabel(TCU_STATIC);
        LASER_WIDTH->setObjectName(QString::fromUtf8("LASER_WIDTH"));
        LASER_WIDTH->setGeometry(QRect(110, 20, 66, 13));
        LASER_WIDTH_EDIT_U = new QLineEdit(TCU_STATIC);
        LASER_WIDTH_EDIT_U->setObjectName(QString::fromUtf8("LASER_WIDTH_EDIT_U"));
        LASER_WIDTH_EDIT_U->setGeometry(QRect(110, 34, 31, 20));
        LASER_WIDTH_EDIT_N = new QLineEdit(TCU_STATIC);
        LASER_WIDTH_EDIT_N->setObjectName(QString::fromUtf8("LASER_WIDTH_EDIT_N"));
        LASER_WIDTH_EDIT_N->setGeometry(QRect(160, 34, 31, 20));
        LASER_WIDTH_U_UNIT = new QLabel(TCU_STATIC);
        LASER_WIDTH_U_UNIT->setObjectName(QString::fromUtf8("LASER_WIDTH_U_UNIT"));
        LASER_WIDTH_U_UNIT->setGeometry(QRect(138, 37, 18, 13));
        LASER_WIDTH_N_UNIT = new QLabel(TCU_STATIC);
        LASER_WIDTH_N_UNIT->setObjectName(QString::fromUtf8("LASER_WIDTH_N_UNIT"));
        LASER_WIDTH_N_UNIT->setGeometry(QRect(194, 37, 12, 13));
        TCU_A = new QLabel(TCU_STATIC);
        TCU_A->setObjectName(QString::fromUtf8("TCU_A"));
        TCU_A->setGeometry(QRect(50, 100, 7, 13));
        TCU_B = new QLabel(TCU_STATIC);
        TCU_B->setObjectName(QString::fromUtf8("TCU_B"));
        TCU_B->setGeometry(QRect(160, 100, 6, 13));
        DELAY_A_UNIT_N = new QLabel(TCU_STATIC);
        DELAY_A_UNIT_N->setObjectName(QString::fromUtf8("DELAY_A_UNIT_N"));
        DELAY_A_UNIT_N->setGeometry(QRect(94, 133, 12, 13));
        DELAY_A_EDIT_N = new QLineEdit(TCU_STATIC);
        DELAY_A_EDIT_N->setObjectName(QString::fromUtf8("DELAY_A_EDIT_N"));
        DELAY_A_EDIT_N->setGeometry(QRect(60, 130, 31, 20));
        DELAY_A_UNIT_U = new QLabel(TCU_STATIC);
        DELAY_A_UNIT_U->setObjectName(QString::fromUtf8("DELAY_A_UNIT_U"));
        DELAY_A_UNIT_U->setGeometry(QRect(38, 133, 18, 13));
        DELAY_A = new QLabel(TCU_STATIC);
        DELAY_A->setObjectName(QString::fromUtf8("DELAY_A"));
        DELAY_A->setGeometry(QRect(40, 116, 31, 13));
        DELAY_A_EDIT_U = new QLineEdit(TCU_STATIC);
        DELAY_A_EDIT_U->setObjectName(QString::fromUtf8("DELAY_A_EDIT_U"));
        DELAY_A_EDIT_U->setGeometry(QRect(10, 130, 31, 20));
        DELAY_B = new QLabel(TCU_STATIC);
        DELAY_B->setObjectName(QString::fromUtf8("DELAY_B"));
        DELAY_B->setGeometry(QRect(150, 116, 31, 13));
        DELAY_B_EDIT_U = new QLineEdit(TCU_STATIC);
        DELAY_B_EDIT_U->setObjectName(QString::fromUtf8("DELAY_B_EDIT_U"));
        DELAY_B_EDIT_U->setGeometry(QRect(120, 130, 31, 20));
        DELAY_B_UNIT_U = new QLabel(TCU_STATIC);
        DELAY_B_UNIT_U->setObjectName(QString::fromUtf8("DELAY_B_UNIT_U"));
        DELAY_B_UNIT_U->setGeometry(QRect(148, 133, 18, 13));
        DELAY_B_UNIT_N = new QLabel(TCU_STATIC);
        DELAY_B_UNIT_N->setObjectName(QString::fromUtf8("DELAY_B_UNIT_N"));
        DELAY_B_UNIT_N->setGeometry(QRect(204, 133, 12, 13));
        DELAY_B_EDIT_N = new QLineEdit(TCU_STATIC);
        DELAY_B_EDIT_N->setObjectName(QString::fromUtf8("DELAY_B_EDIT_N"));
        DELAY_B_EDIT_N->setGeometry(QRect(170, 130, 31, 20));
        GATE_WIDTH_A = new QLabel(TCU_STATIC);
        GATE_WIDTH_A->setObjectName(QString::fromUtf8("GATE_WIDTH_A"));
        GATE_WIDTH_A->setGeometry(QRect(25, 216, 60, 13));
        GATE_WIDTH_B_EDIT_U = new QLineEdit(TCU_STATIC);
        GATE_WIDTH_B_EDIT_U->setObjectName(QString::fromUtf8("GATE_WIDTH_B_EDIT_U"));
        GATE_WIDTH_B_EDIT_U->setGeometry(QRect(120, 230, 31, 20));
        GATE_WIDTH_A_EDIT_U = new QLineEdit(TCU_STATIC);
        GATE_WIDTH_A_EDIT_U->setObjectName(QString::fromUtf8("GATE_WIDTH_A_EDIT_U"));
        GATE_WIDTH_A_EDIT_U->setGeometry(QRect(10, 230, 31, 20));
        GATE_WIDTH_A_UNIT_U = new QLabel(TCU_STATIC);
        GATE_WIDTH_A_UNIT_U->setObjectName(QString::fromUtf8("GATE_WIDTH_A_UNIT_U"));
        GATE_WIDTH_A_UNIT_U->setGeometry(QRect(38, 233, 18, 13));
        GATE_WIDTH_B_EDIT_N = new QLineEdit(TCU_STATIC);
        GATE_WIDTH_B_EDIT_N->setObjectName(QString::fromUtf8("GATE_WIDTH_B_EDIT_N"));
        GATE_WIDTH_B_EDIT_N->setGeometry(QRect(170, 230, 31, 20));
        GATE_WIDTH_A_UNIT_N = new QLabel(TCU_STATIC);
        GATE_WIDTH_A_UNIT_N->setObjectName(QString::fromUtf8("GATE_WIDTH_A_UNIT_N"));
        GATE_WIDTH_A_UNIT_N->setGeometry(QRect(94, 233, 12, 13));
        GATE_WIDTH_B = new QLabel(TCU_STATIC);
        GATE_WIDTH_B->setObjectName(QString::fromUtf8("GATE_WIDTH_B"));
        GATE_WIDTH_B->setGeometry(QRect(135, 216, 60, 13));
        GATE_WIDTH_B_UNIT_N = new QLabel(TCU_STATIC);
        GATE_WIDTH_B_UNIT_N->setObjectName(QString::fromUtf8("GATE_WIDTH_B_UNIT_N"));
        GATE_WIDTH_B_UNIT_N->setGeometry(QRect(204, 233, 12, 13));
        GATE_WIDTH_A_EDIT_N = new QLineEdit(TCU_STATIC);
        GATE_WIDTH_A_EDIT_N->setObjectName(QString::fromUtf8("GATE_WIDTH_A_EDIT_N"));
        GATE_WIDTH_A_EDIT_N->setGeometry(QRect(60, 230, 31, 20));
        GATE_WIDTH_B_UNIT_U = new QLabel(TCU_STATIC);
        GATE_WIDTH_B_UNIT_U->setObjectName(QString::fromUtf8("GATE_WIDTH_B_UNIT_U"));
        GATE_WIDTH_B_UNIT_U->setGeometry(QRect(148, 233, 18, 13));
        LENS_STATIC = new QGroupBox(CENTRAL);
        LENS_STATIC->setObjectName(QString::fromUtf8("LENS_STATIC"));
        LENS_STATIC->setGeometry(QRect(890, 290, 221, 151));
        ZOOM = new QLabel(LENS_STATIC);
        ZOOM->setObjectName(QString::fromUtf8("ZOOM"));
        ZOOM->setGeometry(QRect(42, 20, 24, 13));
        FOCUS = new QLabel(LENS_STATIC);
        FOCUS->setObjectName(QString::fromUtf8("FOCUS"));
        FOCUS->setGeometry(QRect(40, 70, 30, 13));
        ZOOM_IN_BTN = new QPushButton(LENS_STATIC);
        ZOOM_IN_BTN->setObjectName(QString::fromUtf8("ZOOM_IN_BTN"));
        ZOOM_IN_BTN->setGeometry(QRect(30, 40, 21, 20));
        FOCUS_NEAR_BTN = new QPushButton(LENS_STATIC);
        FOCUS_NEAR_BTN->setObjectName(QString::fromUtf8("FOCUS_NEAR_BTN"));
        FOCUS_NEAR_BTN->setGeometry(QRect(30, 90, 21, 20));
        ZOOM_OUT_BTN = new QPushButton(LENS_STATIC);
        ZOOM_OUT_BTN->setObjectName(QString::fromUtf8("ZOOM_OUT_BTN"));
        ZOOM_OUT_BTN->setGeometry(QRect(60, 40, 21, 20));
        FOCUS_FAR_BTN = new QPushButton(LENS_STATIC);
        FOCUS_FAR_BTN->setObjectName(QString::fromUtf8("FOCUS_FAR_BTN"));
        FOCUS_FAR_BTN->setGeometry(QRect(60, 90, 21, 20));
        ZOOM_EDIT = new QLineEdit(LENS_STATIC);
        ZOOM_EDIT->setObjectName(QString::fromUtf8("ZOOM_EDIT"));
        ZOOM_EDIT->setGeometry(QRect(130, 20, 51, 20));
        GET_ZOOM_BTN = new QPushButton(LENS_STATIC);
        GET_ZOOM_BTN->setObjectName(QString::fromUtf8("GET_ZOOM_BTN"));
        GET_ZOOM_BTN->setGeometry(QRect(120, 44, 31, 20));
        SET_ZOOM_BTN = new QPushButton(LENS_STATIC);
        SET_ZOOM_BTN->setObjectName(QString::fromUtf8("SET_ZOOM_BTN"));
        SET_ZOOM_BTN->setGeometry(QRect(160, 44, 31, 20));
        GET_FOCUS_BTN = new QPushButton(LENS_STATIC);
        GET_FOCUS_BTN->setObjectName(QString::fromUtf8("GET_FOCUS_BTN"));
        GET_FOCUS_BTN->setGeometry(QRect(120, 94, 31, 20));
        FOCUS_EDIT = new QLineEdit(LENS_STATIC);
        FOCUS_EDIT->setObjectName(QString::fromUtf8("FOCUS_EDIT"));
        FOCUS_EDIT->setGeometry(QRect(130, 70, 51, 20));
        SET_FOCUS_BTN = new QPushButton(LENS_STATIC);
        SET_FOCUS_BTN->setObjectName(QString::fromUtf8("SET_FOCUS_BTN"));
        SET_FOCUS_BTN->setGeometry(QRect(160, 94, 31, 20));
        FOCUS_SPEED_SLIDER = new QSlider(LENS_STATIC);
        FOCUS_SPEED_SLIDER->setObjectName(QString::fromUtf8("FOCUS_SPEED_SLIDER"));
        FOCUS_SPEED_SLIDER->setGeometry(QRect(30, 124, 111, 20));
        FOCUS_SPEED_SLIDER->setOrientation(Qt::Horizontal);
        FOCUS_SPEED_EDIT = new QLineEdit(LENS_STATIC);
        FOCUS_SPEED_EDIT->setObjectName(QString::fromUtf8("FOCUS_SPEED_EDIT"));
        FOCUS_SPEED_EDIT->setGeometry(QRect(160, 120, 31, 24));
        DATA_EXCHANGE = new QTextEdit(CENTRAL);
        DATA_EXCHANGE->setObjectName(QString::fromUtf8("DATA_EXCHANGE"));
        DATA_EXCHANGE->setGeometry(QRect(260, 460, 221, 171));
        DATA_EXCHANGE->setReadOnly(true);
        DIST_BTN = new QPushButton(CENTRAL);
        DIST_BTN->setObjectName(QString::fromUtf8("DIST_BTN"));
        DIST_BTN->setGeometry(QRect(20, 630, 51, 20));
        DISTANCE = new QLabel(CENTRAL);
        DISTANCE->setObjectName(QString::fromUtf8("DISTANCE"));
        DISTANCE->setGeometry(QRect(500, 530, 71, 16));
        DISTANCE->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        GATE_WIDTH = new QLabel(CENTRAL);
        GATE_WIDTH->setObjectName(QString::fromUtf8("GATE_WIDTH"));
        GATE_WIDTH->setGeometry(QRect(790, 25, 81, 24));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Consolas"));
        font1.setPointSize(16);
        GATE_WIDTH->setFont(font1);
        GATE_WIDTH->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ESTIMATED_2 = new QLabel(CENTRAL);
        ESTIMATED_2->setObjectName(QString::fromUtf8("ESTIMATED_2"));
        ESTIMATED_2->setGeometry(QRect(710, 25, 37, 24));
        ESTIMATED_2->setFont(font1);
        SCAN_BUTTON = new QPushButton(CENTRAL);
        SCAN_BUTTON->setObjectName(QString::fromUtf8("SCAN_BUTTON"));
        SCAN_BUTTON->setGeometry(QRect(20, 600, 51, 21));
        CONTINUE_SCAN_BUTTON = new QPushButton(CENTRAL);
        CONTINUE_SCAN_BUTTON->setObjectName(QString::fromUtf8("CONTINUE_SCAN_BUTTON"));
        CONTINUE_SCAN_BUTTON->setGeometry(QRect(120, 600, 80, 21));
        RESTART_SCAN_BUTTON = new QPushButton(CENTRAL);
        RESTART_SCAN_BUTTON->setObjectName(QString::fromUtf8("RESTART_SCAN_BUTTON"));
        RESTART_SCAN_BUTTON->setGeometry(QRect(120, 630, 80, 21));
        EST_DIST = new QLabel(CENTRAL);
        EST_DIST->setObjectName(QString::fromUtf8("EST_DIST"));
        EST_DIST->setGeometry(QRect(370, 25, 81, 24));
        EST_DIST->setFont(font1);
        EST_DIST->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ESTIMATED = new QLabel(CENTRAL);
        ESTIMATED->setObjectName(QString::fromUtf8("ESTIMATED"));
        ESTIMATED->setGeometry(QRect(290, 25, 48, 24));
        ESTIMATED->setFont(font1);
        CTRL_STATIC = new QGroupBox(CENTRAL);
        CTRL_STATIC->setObjectName(QString::fromUtf8("CTRL_STATIC"));
        CTRL_STATIC->setGeometry(QRect(890, 120, 221, 121));
        DELAY_DIST = new QLabel(CTRL_STATIC);
        DELAY_DIST->setObjectName(QString::fromUtf8("DELAY_DIST"));
        DELAY_DIST->setGeometry(QRect(20, 70, 24, 13));
        MCP = new QLabel(CTRL_STATIC);
        MCP->setObjectName(QString::fromUtf8("MCP"));
        MCP->setGeometry(QRect(20, 20, 18, 13));
        MCP_SLIDER = new QSlider(CTRL_STATIC);
        MCP_SLIDER->setObjectName(QString::fromUtf8("MCP_SLIDER"));
        MCP_SLIDER->setGeometry(QRect(30, 40, 161, 20));
        MCP_SLIDER->setOrientation(Qt::Horizontal);
        DELAY_SLIDER = new QSlider(CTRL_STATIC);
        DELAY_SLIDER->setObjectName(QString::fromUtf8("DELAY_SLIDER"));
        DELAY_SLIDER->setGeometry(QRect(30, 90, 161, 20));
        DELAY_SLIDER->setOrientation(Qt::Horizontal);
        LOGO1 = new QLabel(CENTRAL);
        LOGO1->setObjectName(QString::fromUtf8("LOGO1"));
        LOGO1->setGeometry(QRect(890, 570, 221, 74));
        LOGO1->setPixmap(QPixmap(QString::fromUtf8(":/logo/3.png")));
        LOGO1->setScaledContents(true);
        DUTY_UNIT = new QLabel(CENTRAL);
        DUTY_UNIT->setObjectName(QString::fromUtf8("DUTY_UNIT"));
        DUTY_UNIT->setGeometry(QRect(570, 570, 12, 13));
        GET_PARAMS_BUTTON = new QPushButton(CENTRAL);
        GET_PARAMS_BUTTON->setObjectName(QString::fromUtf8("GET_PARAMS_BUTTON"));
        GET_PARAMS_BUTTON->setGeometry(QRect(500, 590, 80, 20));
        DUTY = new QLabel(CENTRAL);
        DUTY->setObjectName(QString::fromUtf8("DUTY"));
        DUTY->setGeometry(QRect(506, 553, 60, 13));
        DUTY_EDIT = new QLineEdit(CENTRAL);
        DUTY_EDIT->setObjectName(QString::fromUtf8("DUTY_EDIT"));
        DUTY_EDIT->setGeometry(QRect(506, 567, 61, 20));
        NAME = new QLabel(CENTRAL);
        NAME->setObjectName(QString::fromUtf8("NAME"));
        NAME->setGeometry(QRect(960, 50, 81, 35));
        QFont font2;
        font2.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font2.setPointSize(20);
        NAME->setFont(font2);
        LOGO2 = new QLabel(CENTRAL);
        LOGO2->setObjectName(QString::fromUtf8("LOGO2"));
        LOGO2->setGeometry(QRect(960, 470, 90, 90));
        LOGO2->setPixmap(QPixmap(QString::fromUtf8(":/logo/4.png")));
        LOGO2->setScaledContents(true);
        Demo->setCentralWidget(CENTRAL);

        retranslateUi(Demo);

        INITIALIZATION->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Demo);
    } // setupUi

    void retranslateUi(QMainWindow *Demo)
    {
        Demo->setWindowTitle(QApplication::translate("Demo", " YJS", nullptr));
        IMG_GRAB_STATIC->setTitle(QApplication::translate("Demo", "Img Aquisition", nullptr));
        CONTINUOUS_RADIO->setText(QApplication::translate("Demo", "Continuous", nullptr));
        TRIGGER_RADIO->setText(QApplication::translate("Demo", "Trigger", nullptr));
        SOFTWARE_CHECK->setText(QApplication::translate("Demo", "By software", nullptr));
        START_GRABBING_BUTTON->setText(QApplication::translate("Demo", "Start", nullptr));
        STOP_GRABBING_BUTTON->setText(QApplication::translate("Demo", "Stop", nullptr));
        SOFTWARE_TRIGGER_BUTTON->setText(QApplication::translate("Demo", "Grab", nullptr));
        IMG_SAVE_STATIC->setTitle(QApplication::translate("Demo", "Save options", nullptr));
        CUSTOM_FILENAME_CHECK->setText(QApplication::translate("Demo", "Custom filenames", nullptr));
        FILENAME_STATIC->setText(QApplication::translate("Demo", "Save to", nullptr));
        SAVE_BMP_BUTTON->setText(QApplication::translate("Demo", "ORI", nullptr));
        FILE_PATH_BROWSE->setText(QApplication::translate("Demo", "...", nullptr));
        SAVE_AVI_BUTTON->setText(QApplication::translate("Demo", "Record", nullptr));
        SAVE_JPG_BUTTON->setText(QApplication::translate("Demo", "JPG", nullptr));
        SAVE_RESULT_BUTTON->setText(QApplication::translate("Demo", "RES", nullptr));
        PARAMS_STATIC->setTitle(QApplication::translate("Demo", "Parameters", nullptr));
        GAIN_STATIC->setText(QApplication::translate("Demo", "Gain", nullptr));
        SET_PARAMS_BUTTON->setText(QApplication::translate("Demo", "set", nullptr));
        CCD_FREQ->setText(QApplication::translate("Demo", "CCD Freq", nullptr));
        CCD_FREQ_UNIT->setText(QApplication::translate("Demo", "Hz", nullptr));
        TIME_EXPOSURE->setText(QString());
        OPERATION_STATIC->setTitle(QApplication::translate("Demo", "Operations", nullptr));
        IMG_SMOOTH_CHECK->setText(QApplication::translate("Demo", "Smooth-A", nullptr));
        IMG_ENHANCE_CHECK->setText(QApplication::translate("Demo", "DeF-A", nullptr));
        SP_CHECK->setText(QApplication::translate("Demo", "Def-B", nullptr));
        FRAME_AVG_CHECK->setText(QApplication::translate("Demo", "Smooth-B", nullptr));
        SOURCE_DISPLAY->setText(QString());
        CLS_BUTTON->setText(QApplication::translate("Demo", "Cls", nullptr));
        SHUTDOWN_BUTTON->setText(QApplication::translate("Demo", "Turn off", nullptr));
        START_BUTTON->setText(QApplication::translate("Demo", "Turn on", nullptr));
        ENUM_BUTTON->setText(QApplication::translate("Demo", "Search for devices", nullptr));
        INITIALIZATION->setTabText(INITIALIZATION->indexOf(DEVICE), QApplication::translate("Demo", "devices", nullptr));
        TCU_COM->setText(QApplication::translate("Demo", "TCU", nullptr));
        RANGE_COM->setText(QApplication::translate("Demo", "RANGE", nullptr));
        FOCUS_COM->setText(QApplication::translate("Demo", "FOCUS", nullptr));
        THERMO_COM->setText(QApplication::translate("Demo", "THERMO", nullptr));
        TCU_COM_EDIT->setText(QApplication::translate("Demo", "3", nullptr));
        RANGE_COM_EDIT->setText(QApplication::translate("Demo", "7", nullptr));
        FOCUS_COM_EDIT->setText(QApplication::translate("Demo", "8", nullptr));
        THERMO_COM_EDIT->setText(QApplication::translate("Demo", "0", nullptr));
        INITIALIZATION->setTabText(INITIALIZATION->indexOf(COM), QApplication::translate("Demo", "COMs", nullptr));
        TCU_STATIC->setTitle(QApplication::translate("Demo", "TCU", nullptr));
        FREQ->setText(QApplication::translate("Demo", "Frequency", nullptr));
        FREQ_UNIT->setText(QApplication::translate("Demo", "kHz", nullptr));
        LASER_WIDTH->setText(QApplication::translate("Demo", "Laser Width", nullptr));
        LASER_WIDTH_U_UNIT->setText(QApplication::translate("Demo", " \316\274s", nullptr));
        LASER_WIDTH_N_UNIT->setText(QApplication::translate("Demo", "ns", nullptr));
        TCU_A->setText(QApplication::translate("Demo", "A", nullptr));
        TCU_B->setText(QApplication::translate("Demo", "B", nullptr));
        DELAY_A_UNIT_N->setText(QApplication::translate("Demo", "ns", nullptr));
        DELAY_A_UNIT_U->setText(QApplication::translate("Demo", " \316\274s", nullptr));
        DELAY_A->setText(QApplication::translate("Demo", "Delay", nullptr));
        DELAY_B->setText(QApplication::translate("Demo", "Delay", nullptr));
        DELAY_B_UNIT_U->setText(QApplication::translate("Demo", " \316\274s", nullptr));
        DELAY_B_UNIT_N->setText(QApplication::translate("Demo", "ns", nullptr));
        GATE_WIDTH_A->setText(QApplication::translate("Demo", "Gate Width", nullptr));
        GATE_WIDTH_A_UNIT_U->setText(QApplication::translate("Demo", " \316\274s", nullptr));
        GATE_WIDTH_A_UNIT_N->setText(QApplication::translate("Demo", "ns", nullptr));
        GATE_WIDTH_B->setText(QApplication::translate("Demo", "Gate Width", nullptr));
        GATE_WIDTH_B_UNIT_N->setText(QApplication::translate("Demo", "ns", nullptr));
        GATE_WIDTH_B_UNIT_U->setText(QApplication::translate("Demo", " \316\274s", nullptr));
        LENS_STATIC->setTitle(QApplication::translate("Demo", "Lens", nullptr));
        ZOOM->setText(QApplication::translate("Demo", "Zoom", nullptr));
        FOCUS->setText(QApplication::translate("Demo", "Focus", nullptr));
        ZOOM_IN_BTN->setText(QApplication::translate("Demo", "+", nullptr));
        FOCUS_NEAR_BTN->setText(QApplication::translate("Demo", "+", nullptr));
        ZOOM_OUT_BTN->setText(QApplication::translate("Demo", "-", nullptr));
        FOCUS_FAR_BTN->setText(QApplication::translate("Demo", "-", nullptr));
        GET_ZOOM_BTN->setText(QApplication::translate("Demo", "get", nullptr));
        SET_ZOOM_BTN->setText(QApplication::translate("Demo", "set", nullptr));
        GET_FOCUS_BTN->setText(QApplication::translate("Demo", "get", nullptr));
        SET_FOCUS_BTN->setText(QApplication::translate("Demo", "set", nullptr));
        FOCUS_SPEED_EDIT->setText(QApplication::translate("Demo", "5", nullptr));
        DIST_BTN->setText(QApplication::translate("Demo", "Dist", nullptr));
        DISTANCE->setText(QString());
        GATE_WIDTH->setText(QString());
        ESTIMATED_2->setText(QApplication::translate("Demo", "DOV", nullptr));
        SCAN_BUTTON->setText(QApplication::translate("Demo", "Scan", nullptr));
        CONTINUE_SCAN_BUTTON->setText(QApplication::translate("Demo", "Continue", nullptr));
        RESTART_SCAN_BUTTON->setText(QApplication::translate("Demo", "Restart", nullptr));
        EST_DIST->setText(QString());
        ESTIMATED->setText(QApplication::translate("Demo", "DIST", nullptr));
        CTRL_STATIC->setTitle(QApplication::translate("Demo", "Ctrl", nullptr));
        DELAY_DIST->setText(QApplication::translate("Demo", "Dist", nullptr));
        MCP->setText(QApplication::translate("Demo", "MCP", nullptr));
        LOGO1->setText(QString());
        DUTY_UNIT->setText(QApplication::translate("Demo", "ms", nullptr));
        GET_PARAMS_BUTTON->setText(QApplication::translate("Demo", "Get params", nullptr));
        DUTY->setText(QApplication::translate("Demo", "Time Expo.", nullptr));
        NAME->setText(QApplication::translate("Demo", "\347\234\274\351\225\234\350\233\207", nullptr));
        LOGO2->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Demo: public Ui_Demo {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DEMO_H
