/********************************************************************************
** Form generated from reading UI file 'demo_dev.ui'
**
** Created by: Qt User Interface Compiler version 5.12.10
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DEMO_DEV_H
#define UI_DEMO_DEV_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>
#include "mywidget.h"

QT_BEGIN_NAMESPACE

class Ui_Demo
{
public:
    QAction *ACTION_IMPORT;
    QAction *ACTION_EXPORT;
    QAction *ACTION_DEVICES;
    QAction *ACTION_SERIAL_PORTS;
    QWidget *CENTRAL;
    QFrame *LEFT;
    QGroupBox *PARAMS_STATIC;
    QLabel *GAIN_STATIC;
    QLineEdit *GAIN_EDIT;
    QSlider *GAIN_SLIDER;
    QPushButton *SET_PARAMS_BUTTON;
    QPushButton *GET_PARAMS_BUTTON;
    QLineEdit *DUTY_EDIT;
    QLineEdit *CCD_FREQ_EDIT;
    QLabel *DUTY_UNIT;
    QLabel *DUTY;
    QLabel *CCD_FREQ;
    QLabel *CCD_FREQ_UNIT;
    QGroupBox *IMG_GRAB_STATIC;
    QRadioButton *CONTINUOUS_RADIO;
    QRadioButton *TRIGGER_RADIO;
    QCheckBox *SOFTWARE_CHECK;
    QPushButton *START_GRABBING_BUTTON;
    QPushButton *STOP_GRABBING_BUTTON;
    QPushButton *SOFTWARE_TRIGGER_BUTTON;
    QTabWidget *INITIALIZATION;
    QWidget *DEVICE;
    QPushButton *SHUTDOWN_BUTTON;
    QPushButton *START_BUTTON;
    QPushButton *ENUM_BUTTON;
    QWidget *COM;
    QLabel *TCU_COM;
    QLabel *RANGE_COM;
    QLabel *FOCUS_COM;
    QLabel *LASER_COM;
    QLineEdit *TCU_COM_EDIT;
    QLineEdit *RANGE_COM_EDIT;
    QLineEdit *FOCUS_COM_EDIT;
    QLineEdit *LASER_COM_EDIT;
    QTextEdit *DATA_EXCHANGE;
    QGroupBox *LASER_STATIC;
    QLineEdit *CURRENT_EDIT;
    QPushButton *LASER_ZOOM_IN_BTN;
    QLabel *LASER_ZOOM_LABEL;
    QPushButton *LASER_ZOOM_OUT_BTN;
    QPushButton *LASER_BTN;
    QLabel *DISTANCE;
    QPushButton *DIST_BTN;
    QRadioButton *COM_DATA_RADIO;
    QRadioButton *HISTOGRAM_RADIO;
    QLabel *HIST_DISPLAY;
    QRadioButton *ROI_RADIO;
    QFrame *MID;
    QGroupBox *CTRL_STATIC;
    QLabel *LOGO1;
    QLabel *NAME;
    QLabel *LOGO2;
    Display *SOURCE_DISPLAY;
    QCheckBox *CENTER_CHECK;
    Ruler *RULER_H;
    Ruler *RULER_V;
    Tools *DRAG_TOOL;
    Tools *SELECT_TOOL;
    Coordinate *CURR_COORD;
    Coordinate *START_COORD;
    Coordinate *SHAPE_INFO;
    QCheckBox *INFO_CHECK;
    QTableWidget *ROI_TABLE;
    QFrame *RIGHT;
    QGroupBox *LENS_STATIC;
    QLabel *ZOOM_LABEL;
    QLabel *FOCUS_LABEL;
    QPushButton *ZOOM_IN_BTN;
    QPushButton *FOCUS_NEAR_BTN;
    QPushButton *ZOOM_OUT_BTN;
    QPushButton *FOCUS_FAR_BTN;
    QSlider *FOCUS_SPEED_SLIDER;
    QLineEdit *FOCUS_SPEED_EDIT;
    QLineEdit *ZOOM_EDIT;
    QLineEdit *FOCUS_EDIT;
    QPushButton *GET_LENS_PARAM_BTN;
    QPushButton *AUTO_FOCUS_BTN;
    QGroupBox *TCU_STATIC;
    QLineEdit *FREQ_EDIT;
    QLabel *FREQ;
    QLabel *FREQ_UNIT;
    QLabel *LASER_WIDTH;
    QLineEdit *LASER_WIDTH_EDIT_U;
    QLineEdit *LASER_WIDTH_EDIT_N;
    QLabel *LASER_WIDTH_U_UNIT;
    QLabel *LASER_WIDTH_N_UNIT;
    QSlider *MCP_SLIDER;
    QLabel *MCP;
    QLabel *TCU_A;
    QLabel *TCU_B;
    QLabel *DELAY_A_UNIT_N;
    QLineEdit *DELAY_A_EDIT_N;
    QLabel *DELAY_A_UNIT_U;
    QLabel *DELAY_A;
    QLineEdit *DELAY_A_EDIT_U;
    QLabel *DELAY_B;
    QLineEdit *DELAY_B_EDIT_U;
    QLabel *DELAY_B_UNIT_U;
    QLabel *DELAY_B_UNIT_N;
    QLineEdit *DELAY_B_EDIT_N;
    QLabel *GATE_WIDTH_A;
    QLineEdit *GATE_WIDTH_A_EDIT_U;
    QLabel *GATE_WIDTH_A_UNIT_U;
    QLineEdit *STRIDE_EDIT;
    QLabel *GATE_WIDTH_A_UNIT_N;
    QLabel *STRIDE;
    QLabel *STRIDE_UNIT;
    QLineEdit *GATE_WIDTH_A_EDIT_N;
    QLabel *ESTIMATED;
    QLabel *EST_DIST;
    QSlider *DELAY_SLIDER;
    QLineEdit *DELAY_N_EDIT_N;
    QLabel *DELAY_N_UNIT_N;
    QLabel *DELAY_N;
    QLabel *ESTIMATED_2;
    QLabel *GATE_WIDTH;
    QGroupBox *OPERATION_STATIC;
    QCheckBox *IMG_ENHANCE_CHECK;
    QComboBox *ENHANCE_OPTIONS;
    QCheckBox *SP_CHECK;
    QComboBox *SP_OPTIONS;
    QCheckBox *FRAME_AVG_CHECK;
    QComboBox *FRAME_AVG_OPTIONS;
    QCheckBox *IMG_3D_CHECK;
    QLineEdit *RANGE_THRESH_EDIT;
    QSlider *CONTRAST_SLIDER;
    QSlider *BRIGHTNESS_SLIDER;
    QLabel *BRIGHTNESS_LABEL;
    QLabel *CONTRAST_LABEL;
    QPushButton *RESTART_SCAN_BUTTON;
    QPushButton *CONTINUE_SCAN_BUTTON;
    QPushButton *SCAN_BUTTON;
    QGroupBox *IMG_SAVE_STATIC;
    QPushButton *SAVE_BMP_BUTTON;
    QLineEdit *FILE_PATH_EDIT;
    QToolButton *FILE_PATH_BROWSE;
    QPushButton *SAVE_AVI_BUTTON;
    QPushButton *SAVE_FINAL_BUTTON;
    QPushButton *SAVE_RESULT_BUTTON;
    QLabel *CAPTURE_LABEL;
    QLabel *RECORD_LABEL;
    QPushButton *HIDE_BTN;
    TitleBar *TITLE;

    void setupUi(QMainWindow *Demo)
    {
        if (Demo->objectName().isEmpty())
            Demo->setObjectName(QString::fromUtf8("Demo"));
        Demo->resize(1130, 680);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(Demo->sizePolicy().hasHeightForWidth());
        Demo->setSizePolicy(sizePolicy);
        Demo->setMinimumSize(QSize(1130, 680));
        QFont font;
        font.setFamily(QString::fromUtf8("Consolas"));
        font.setPointSize(8);
        font.setBold(false);
        font.setWeight(50);
        Demo->setFont(font);
        Demo->setMouseTracking(true);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/logo/1.png"), QSize(), QIcon::Normal, QIcon::Off);
        Demo->setWindowIcon(icon);
        Demo->setStyleSheet(QString::fromUtf8(""));
        Demo->setTabShape(QTabWidget::Rounded);
        ACTION_IMPORT = new QAction(Demo);
        ACTION_IMPORT->setObjectName(QString::fromUtf8("ACTION_IMPORT"));
        ACTION_EXPORT = new QAction(Demo);
        ACTION_EXPORT->setObjectName(QString::fromUtf8("ACTION_EXPORT"));
        ACTION_DEVICES = new QAction(Demo);
        ACTION_DEVICES->setObjectName(QString::fromUtf8("ACTION_DEVICES"));
        ACTION_SERIAL_PORTS = new QAction(Demo);
        ACTION_SERIAL_PORTS->setObjectName(QString::fromUtf8("ACTION_SERIAL_PORTS"));
        CENTRAL = new QWidget(Demo);
        CENTRAL->setObjectName(QString::fromUtf8("CENTRAL"));
        CENTRAL->setMouseTracking(false);
        CENTRAL->setStyleSheet(QString::fromUtf8(""));
        LEFT = new QFrame(CENTRAL);
        LEFT->setObjectName(QString::fromUtf8("LEFT"));
        LEFT->setGeometry(QRect(10, 40, 210, 630));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Consolas"));
        font1.setPointSize(9);
        font1.setBold(false);
        font1.setWeight(50);
        LEFT->setFont(font1);
        LEFT->setMouseTracking(false);
        LEFT->setFrameShape(QFrame::NoFrame);
        LEFT->setFrameShadow(QFrame::Plain);
        PARAMS_STATIC = new QGroupBox(LEFT);
        PARAMS_STATIC->setObjectName(QString::fromUtf8("PARAMS_STATIC"));
        PARAMS_STATIC->setGeometry(QRect(10, 220, 191, 131));
        PARAMS_STATIC->setFont(font1);
        PARAMS_STATIC->setMouseTracking(false);
        GAIN_STATIC = new QLabel(PARAMS_STATIC);
        GAIN_STATIC->setObjectName(QString::fromUtf8("GAIN_STATIC"));
        GAIN_STATIC->setGeometry(QRect(20, 87, 28, 14));
        GAIN_STATIC->setFont(font1);
        GAIN_STATIC->setMouseTracking(false);
        GAIN_STATIC->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        GAIN_EDIT = new QLineEdit(PARAMS_STATIC);
        GAIN_EDIT->setObjectName(QString::fromUtf8("GAIN_EDIT"));
        GAIN_EDIT->setGeometry(QRect(130, 84, 51, 20));
        GAIN_EDIT->setFont(font1);
        GAIN_EDIT->setMouseTracking(false);
        GAIN_SLIDER = new QSlider(PARAMS_STATIC);
        GAIN_SLIDER->setObjectName(QString::fromUtf8("GAIN_SLIDER"));
        GAIN_SLIDER->setGeometry(QRect(20, 105, 151, 20));
        GAIN_SLIDER->setFont(font1);
        GAIN_SLIDER->setMouseTracking(false);
        GAIN_SLIDER->setOrientation(Qt::Horizontal);
        SET_PARAMS_BUTTON = new QPushButton(PARAMS_STATIC);
        SET_PARAMS_BUTTON->setObjectName(QString::fromUtf8("SET_PARAMS_BUTTON"));
        SET_PARAMS_BUTTON->setGeometry(QRect(100, 60, 80, 20));
        SET_PARAMS_BUTTON->setFont(font1);
        SET_PARAMS_BUTTON->setMouseTracking(false);
        GET_PARAMS_BUTTON = new QPushButton(PARAMS_STATIC);
        GET_PARAMS_BUTTON->setObjectName(QString::fromUtf8("GET_PARAMS_BUTTON"));
        GET_PARAMS_BUTTON->setGeometry(QRect(10, 60, 80, 20));
        GET_PARAMS_BUTTON->setFont(font1);
        GET_PARAMS_BUTTON->setMouseTracking(false);
        DUTY_EDIT = new QLineEdit(PARAMS_STATIC);
        DUTY_EDIT->setObjectName(QString::fromUtf8("DUTY_EDIT"));
        DUTY_EDIT->setGeometry(QRect(106, 34, 61, 20));
        DUTY_EDIT->setFont(font1);
        DUTY_EDIT->setMouseTracking(false);
        CCD_FREQ_EDIT = new QLineEdit(PARAMS_STATIC);
        CCD_FREQ_EDIT->setObjectName(QString::fromUtf8("CCD_FREQ_EDIT"));
        CCD_FREQ_EDIT->setGeometry(QRect(16, 34, 61, 20));
        CCD_FREQ_EDIT->setFont(font1);
        CCD_FREQ_EDIT->setMouseTracking(false);
        DUTY_UNIT = new QLabel(PARAMS_STATIC);
        DUTY_UNIT->setObjectName(QString::fromUtf8("DUTY_UNIT"));
        DUTY_UNIT->setGeometry(QRect(170, 37, 14, 14));
        DUTY_UNIT->setFont(font1);
        DUTY_UNIT->setMouseTracking(false);
        DUTY = new QLabel(PARAMS_STATIC);
        DUTY->setObjectName(QString::fromUtf8("DUTY"));
        DUTY->setGeometry(QRect(106, 20, 70, 14));
        DUTY->setFont(font1);
        DUTY->setMouseTracking(false);
        DUTY->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        CCD_FREQ = new QLabel(PARAMS_STATIC);
        CCD_FREQ->setObjectName(QString::fromUtf8("CCD_FREQ"));
        CCD_FREQ->setGeometry(QRect(16, 20, 56, 14));
        CCD_FREQ->setFont(font1);
        CCD_FREQ->setMouseTracking(false);
        CCD_FREQ->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        CCD_FREQ_UNIT = new QLabel(PARAMS_STATIC);
        CCD_FREQ_UNIT->setObjectName(QString::fromUtf8("CCD_FREQ_UNIT"));
        CCD_FREQ_UNIT->setGeometry(QRect(80, 37, 14, 14));
        CCD_FREQ_UNIT->setFont(font1);
        CCD_FREQ_UNIT->setMouseTracking(false);
        IMG_GRAB_STATIC = new QGroupBox(LEFT);
        IMG_GRAB_STATIC->setObjectName(QString::fromUtf8("IMG_GRAB_STATIC"));
        IMG_GRAB_STATIC->setGeometry(QRect(10, 120, 191, 91));
        IMG_GRAB_STATIC->setFont(font1);
        IMG_GRAB_STATIC->setMouseTracking(false);
        CONTINUOUS_RADIO = new QRadioButton(IMG_GRAB_STATIC);
        CONTINUOUS_RADIO->setObjectName(QString::fromUtf8("CONTINUOUS_RADIO"));
        CONTINUOUS_RADIO->setGeometry(QRect(10, 20, 95, 20));
        CONTINUOUS_RADIO->setFont(font1);
        CONTINUOUS_RADIO->setMouseTracking(false);
        TRIGGER_RADIO = new QRadioButton(IMG_GRAB_STATIC);
        TRIGGER_RADIO->setObjectName(QString::fromUtf8("TRIGGER_RADIO"));
        TRIGGER_RADIO->setGeometry(QRect(10, 40, 74, 20));
        TRIGGER_RADIO->setFont(font1);
        TRIGGER_RADIO->setMouseTracking(false);
        SOFTWARE_CHECK = new QCheckBox(IMG_GRAB_STATIC);
        SOFTWARE_CHECK->setObjectName(QString::fromUtf8("SOFTWARE_CHECK"));
        SOFTWARE_CHECK->setGeometry(QRect(20, 60, 102, 20));
        SOFTWARE_CHECK->setFont(font1);
        SOFTWARE_CHECK->setMouseTracking(false);
        START_GRABBING_BUTTON = new QPushButton(IMG_GRAB_STATIC);
        START_GRABBING_BUTTON->setObjectName(QString::fromUtf8("START_GRABBING_BUTTON"));
        START_GRABBING_BUTTON->setGeometry(QRect(120, 20, 61, 20));
        START_GRABBING_BUTTON->setFont(font1);
        START_GRABBING_BUTTON->setMouseTracking(false);
        STOP_GRABBING_BUTTON = new QPushButton(IMG_GRAB_STATIC);
        STOP_GRABBING_BUTTON->setObjectName(QString::fromUtf8("STOP_GRABBING_BUTTON"));
        STOP_GRABBING_BUTTON->setGeometry(QRect(120, 40, 61, 20));
        STOP_GRABBING_BUTTON->setFont(font1);
        STOP_GRABBING_BUTTON->setMouseTracking(false);
        SOFTWARE_TRIGGER_BUTTON = new QPushButton(IMG_GRAB_STATIC);
        SOFTWARE_TRIGGER_BUTTON->setObjectName(QString::fromUtf8("SOFTWARE_TRIGGER_BUTTON"));
        SOFTWARE_TRIGGER_BUTTON->setGeometry(QRect(130, 60, 41, 20));
        SOFTWARE_TRIGGER_BUTTON->setFont(font1);
        SOFTWARE_TRIGGER_BUTTON->setMouseTracking(false);
        INITIALIZATION = new QTabWidget(LEFT);
        INITIALIZATION->setObjectName(QString::fromUtf8("INITIALIZATION"));
        INITIALIZATION->setGeometry(QRect(10, 10, 191, 101));
        INITIALIZATION->setFont(font1);
        INITIALIZATION->setMouseTracking(false);
        INITIALIZATION->setStyleSheet(QString::fromUtf8(""));
        INITIALIZATION->setUsesScrollButtons(true);
        DEVICE = new QWidget();
        DEVICE->setObjectName(QString::fromUtf8("DEVICE"));
        SHUTDOWN_BUTTON = new QPushButton(DEVICE);
        SHUTDOWN_BUTTON->setObjectName(QString::fromUtf8("SHUTDOWN_BUTTON"));
        SHUTDOWN_BUTTON->setGeometry(QRect(100, 45, 81, 20));
        SHUTDOWN_BUTTON->setFont(font1);
        SHUTDOWN_BUTTON->setMouseTracking(false);
        START_BUTTON = new QPushButton(DEVICE);
        START_BUTTON->setObjectName(QString::fromUtf8("START_BUTTON"));
        START_BUTTON->setGeometry(QRect(10, 45, 81, 20));
        START_BUTTON->setFont(font1);
        START_BUTTON->setMouseTracking(false);
        ENUM_BUTTON = new QPushButton(DEVICE);
        ENUM_BUTTON->setObjectName(QString::fromUtf8("ENUM_BUTTON"));
        ENUM_BUTTON->setGeometry(QRect(10, 15, 171, 20));
        ENUM_BUTTON->setFont(font1);
        ENUM_BUTTON->setMouseTracking(false);
        INITIALIZATION->addTab(DEVICE, QString());
        COM = new QWidget();
        COM->setObjectName(QString::fromUtf8("COM"));
        TCU_COM = new QLabel(COM);
        TCU_COM->setObjectName(QString::fromUtf8("TCU_COM"));
        TCU_COM->setGeometry(QRect(10, 13, 21, 14));
        RANGE_COM = new QLabel(COM);
        RANGE_COM->setObjectName(QString::fromUtf8("RANGE_COM"));
        RANGE_COM->setGeometry(QRect(100, 13, 35, 14));
        FOCUS_COM = new QLabel(COM);
        FOCUS_COM->setObjectName(QString::fromUtf8("FOCUS_COM"));
        FOCUS_COM->setGeometry(QRect(10, 43, 35, 14));
        LASER_COM = new QLabel(COM);
        LASER_COM->setObjectName(QString::fromUtf8("LASER_COM"));
        LASER_COM->setGeometry(QRect(100, 43, 35, 14));
        TCU_COM_EDIT = new QLineEdit(COM);
        TCU_COM_EDIT->setObjectName(QString::fromUtf8("TCU_COM_EDIT"));
        TCU_COM_EDIT->setGeometry(QRect(50, 10, 31, 20));
        TCU_COM_EDIT->setMouseTracking(false);
        RANGE_COM_EDIT = new QLineEdit(COM);
        RANGE_COM_EDIT->setObjectName(QString::fromUtf8("RANGE_COM_EDIT"));
        RANGE_COM_EDIT->setGeometry(QRect(140, 10, 31, 20));
        RANGE_COM_EDIT->setMouseTracking(false);
        FOCUS_COM_EDIT = new QLineEdit(COM);
        FOCUS_COM_EDIT->setObjectName(QString::fromUtf8("FOCUS_COM_EDIT"));
        FOCUS_COM_EDIT->setGeometry(QRect(50, 40, 31, 20));
        FOCUS_COM_EDIT->setMouseTracking(false);
        LASER_COM_EDIT = new QLineEdit(COM);
        LASER_COM_EDIT->setObjectName(QString::fromUtf8("LASER_COM_EDIT"));
        LASER_COM_EDIT->setGeometry(QRect(140, 40, 31, 20));
        LASER_COM_EDIT->setMouseTracking(false);
        INITIALIZATION->addTab(COM, QString());
        DATA_EXCHANGE = new QTextEdit(LEFT);
        DATA_EXCHANGE->setObjectName(QString::fromUtf8("DATA_EXCHANGE"));
        DATA_EXCHANGE->setGeometry(QRect(10, 460, 191, 161));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Consolas"));
        font2.setPointSize(8);
        font2.setBold(true);
        font2.setWeight(75);
        DATA_EXCHANGE->setFont(font2);
        DATA_EXCHANGE->setMouseTracking(false);
        DATA_EXCHANGE->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        DATA_EXCHANGE->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        DATA_EXCHANGE->setReadOnly(true);
        LASER_STATIC = new QGroupBox(LEFT);
        LASER_STATIC->setObjectName(QString::fromUtf8("LASER_STATIC"));
        LASER_STATIC->setGeometry(QRect(10, 360, 191, 61));
        LASER_STATIC->setFont(font1);
        LASER_STATIC->setMouseTracking(false);
        CURRENT_EDIT = new QLineEdit(LASER_STATIC);
        CURRENT_EDIT->setObjectName(QString::fromUtf8("CURRENT_EDIT"));
        CURRENT_EDIT->setEnabled(false);
        CURRENT_EDIT->setGeometry(QRect(10, 15, 31, 20));
        CURRENT_EDIT->setFont(font1);
        CURRENT_EDIT->setMouseTracking(false);
        LASER_ZOOM_IN_BTN = new QPushButton(LASER_STATIC);
        LASER_ZOOM_IN_BTN->setObjectName(QString::fromUtf8("LASER_ZOOM_IN_BTN"));
        LASER_ZOOM_IN_BTN->setEnabled(true);
        LASER_ZOOM_IN_BTN->setGeometry(QRect(50, 35, 20, 20));
        LASER_ZOOM_IN_BTN->setFont(font1);
        LASER_ZOOM_IN_BTN->setMouseTracking(false);
        LASER_ZOOM_LABEL = new QLabel(LASER_STATIC);
        LASER_ZOOM_LABEL->setObjectName(QString::fromUtf8("LASER_ZOOM_LABEL"));
        LASER_ZOOM_LABEL->setGeometry(QRect(56, 20, 28, 14));
        LASER_ZOOM_LABEL->setFont(font1);
        LASER_ZOOM_LABEL->setMouseTracking(false);
        LASER_ZOOM_LABEL->setAlignment(Qt::AlignCenter);
        LASER_ZOOM_OUT_BTN = new QPushButton(LASER_STATIC);
        LASER_ZOOM_OUT_BTN->setObjectName(QString::fromUtf8("LASER_ZOOM_OUT_BTN"));
        LASER_ZOOM_OUT_BTN->setEnabled(true);
        LASER_ZOOM_OUT_BTN->setGeometry(QRect(70, 35, 20, 20));
        LASER_ZOOM_OUT_BTN->setFont(font1);
        LASER_ZOOM_OUT_BTN->setMouseTracking(false);
        LASER_BTN = new QPushButton(LASER_STATIC);
        LASER_BTN->setObjectName(QString::fromUtf8("LASER_BTN"));
        LASER_BTN->setEnabled(true);
        LASER_BTN->setGeometry(QRect(10, 35, 31, 20));
        LASER_BTN->setFont(font1);
        LASER_BTN->setMouseTracking(false);
        DISTANCE = new QLabel(LASER_STATIC);
        DISTANCE->setObjectName(QString::fromUtf8("DISTANCE"));
        DISTANCE->setGeometry(QRect(110, 40, 71, 16));
        DISTANCE->setFont(font1);
        DISTANCE->setMouseTracking(false);
        DISTANCE->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        DIST_BTN = new QPushButton(LASER_STATIC);
        DIST_BTN->setObjectName(QString::fromUtf8("DIST_BTN"));
        DIST_BTN->setGeometry(QRect(110, 20, 71, 20));
        DIST_BTN->setFont(font1);
        DIST_BTN->setMouseTracking(false);
        COM_DATA_RADIO = new QRadioButton(LEFT);
        COM_DATA_RADIO->setObjectName(QString::fromUtf8("COM_DATA_RADIO"));
        COM_DATA_RADIO->setGeometry(QRect(10, 440, 53, 20));
        COM_DATA_RADIO->setFont(font1);
        HISTOGRAM_RADIO = new QRadioButton(LEFT);
        HISTOGRAM_RADIO->setObjectName(QString::fromUtf8("HISTOGRAM_RADIO"));
        HISTOGRAM_RADIO->setGeometry(QRect(70, 440, 53, 20));
        HISTOGRAM_RADIO->setFont(font1);
        HIST_DISPLAY = new QLabel(LEFT);
        HIST_DISPLAY->setObjectName(QString::fromUtf8("HIST_DISPLAY"));
        HIST_DISPLAY->setGeometry(QRect(10, 460, 191, 161));
        HIST_DISPLAY->setFont(font1);
        HIST_DISPLAY->setFrameShape(QFrame::NoFrame);
        ROI_RADIO = new QRadioButton(LEFT);
        ROI_RADIO->setObjectName(QString::fromUtf8("ROI_RADIO"));
        ROI_RADIO->setGeometry(QRect(130, 440, 46, 20));
        HIST_DISPLAY->raise();
        PARAMS_STATIC->raise();
        IMG_GRAB_STATIC->raise();
        INITIALIZATION->raise();
        DATA_EXCHANGE->raise();
        LASER_STATIC->raise();
        COM_DATA_RADIO->raise();
        HISTOGRAM_RADIO->raise();
        ROI_RADIO->raise();
        MID = new QFrame(CENTRAL);
        MID->setObjectName(QString::fromUtf8("MID"));
        MID->setGeometry(QRect(220, 40, 660, 630));
        MID->setFont(font1);
        MID->setMouseTracking(false);
        MID->setStyleSheet(QString::fromUtf8(""));
        MID->setFrameShape(QFrame::NoFrame);
        MID->setFrameShadow(QFrame::Plain);
        CTRL_STATIC = new QGroupBox(MID);
        CTRL_STATIC->setObjectName(QString::fromUtf8("CTRL_STATIC"));
        CTRL_STATIC->setGeometry(QRect(270, 530, 120, 80));
        CTRL_STATIC->setFont(font1);
        CTRL_STATIC->setMouseTracking(false);
        LOGO1 = new QLabel(CTRL_STATIC);
        LOGO1->setObjectName(QString::fromUtf8("LOGO1"));
        LOGO1->setGeometry(QRect(20, 40, 81, 18));
        LOGO1->setFont(font1);
        LOGO1->setMouseTracking(false);
        NAME = new QLabel(CTRL_STATIC);
        NAME->setObjectName(QString::fromUtf8("NAME"));
        NAME->setGeometry(QRect(20, 20, 81, 18));
        NAME->setFont(font1);
        NAME->setMouseTracking(false);
        NAME->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        LOGO2 = new QLabel(CTRL_STATIC);
        LOGO2->setObjectName(QString::fromUtf8("LOGO2"));
        LOGO2->setGeometry(QRect(20, 60, 81, 18));
        LOGO2->setFont(font1);
        LOGO2->setMouseTracking(false);
        SOURCE_DISPLAY = new Display(MID);
        SOURCE_DISPLAY->setObjectName(QString::fromUtf8("SOURCE_DISPLAY"));
        SOURCE_DISPLAY->setGeometry(QRect(10, 40, 640, 400));
        SOURCE_DISPLAY->setFont(font1);
        SOURCE_DISPLAY->setMouseTracking(true);
        SOURCE_DISPLAY->setFrameShape(QFrame::Box);
        CENTER_CHECK = new QCheckBox(MID);
        CENTER_CHECK->setObjectName(QString::fromUtf8("CENTER_CHECK"));
        CENTER_CHECK->setGeometry(QRect(590, 20, 67, 20));
        CENTER_CHECK->setFont(font1);
        CENTER_CHECK->setMouseTracking(false);
        RULER_H = new Ruler(MID);
        RULER_H->setObjectName(QString::fromUtf8("RULER_H"));
        RULER_H->setGeometry(QRect(10, 430, 640, 32));
        RULER_H->setFont(font1);
        RULER_H->setMouseTracking(false);
        RULER_V = new Ruler(MID);
        RULER_V->setObjectName(QString::fromUtf8("RULER_V"));
        RULER_V->setGeometry(QRect(640, 40, 32, 400));
        RULER_V->setFont(font1);
        RULER_V->setMouseTracking(false);
        DRAG_TOOL = new Tools(MID);
        DRAG_TOOL->setObjectName(QString::fromUtf8("DRAG_TOOL"));
        DRAG_TOOL->setGeometry(QRect(10, 15, 20, 20));
        DRAG_TOOL->setFont(font1);
        SELECT_TOOL = new Tools(MID);
        SELECT_TOOL->setObjectName(QString::fromUtf8("SELECT_TOOL"));
        SELECT_TOOL->setGeometry(QRect(40, 15, 20, 20));
        SELECT_TOOL->setFont(font1);
        CURR_COORD = new Coordinate(MID);
        CURR_COORD->setObjectName(QString::fromUtf8("CURR_COORD"));
        CURR_COORD->setGeometry(QRect(90, 5, 90, 30));
        CURR_COORD->setFont(font1);
        CURR_COORD->setFrameShape(QFrame::NoFrame);
        CURR_COORD->setFrameShadow(QFrame::Raised);
        START_COORD = new Coordinate(MID);
        START_COORD->setObjectName(QString::fromUtf8("START_COORD"));
        START_COORD->setGeometry(QRect(200, 5, 90, 30));
        START_COORD->setFont(font1);
        START_COORD->setFrameShape(QFrame::NoFrame);
        START_COORD->setFrameShadow(QFrame::Raised);
        SHAPE_INFO = new Coordinate(MID);
        SHAPE_INFO->setObjectName(QString::fromUtf8("SHAPE_INFO"));
        SHAPE_INFO->setGeometry(QRect(310, 5, 90, 30));
        SHAPE_INFO->setFont(font1);
        SHAPE_INFO->setFrameShape(QFrame::NoFrame);
        SHAPE_INFO->setFrameShadow(QFrame::Raised);
        INFO_CHECK = new QCheckBox(MID);
        INFO_CHECK->setObjectName(QString::fromUtf8("INFO_CHECK"));
        INFO_CHECK->setGeometry(QRect(590, 0, 53, 20));
        INFO_CHECK->setFont(font1);
        INFO_CHECK->setMouseTracking(false);
        ROI_TABLE = new QTableWidget(MID);
        if (ROI_TABLE->columnCount() < 2)
            ROI_TABLE->setColumnCount(2);
        if (ROI_TABLE->rowCount() < 4)
            ROI_TABLE->setRowCount(4);
        ROI_TABLE->setObjectName(QString::fromUtf8("ROI_TABLE"));
        ROI_TABLE->setGeometry(QRect(20, 460, 191, 161));
        ROI_TABLE->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        ROI_TABLE->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        ROI_TABLE->setRowCount(4);
        ROI_TABLE->setColumnCount(2);
        ROI_TABLE->verticalHeader()->setVisible(true);
        RIGHT = new QFrame(CENTRAL);
        RIGHT->setObjectName(QString::fromUtf8("RIGHT"));
        RIGHT->setGeometry(QRect(880, 40, 240, 630));
        RIGHT->setFont(font1);
        RIGHT->setMouseTracking(false);
        RIGHT->setFrameShape(QFrame::NoFrame);
        RIGHT->setFrameShadow(QFrame::Plain);
        LENS_STATIC = new QGroupBox(RIGHT);
        LENS_STATIC->setObjectName(QString::fromUtf8("LENS_STATIC"));
        LENS_STATIC->setGeometry(QRect(10, 260, 221, 96));
        LENS_STATIC->setFont(font1);
        LENS_STATIC->setMouseTracking(false);
        ZOOM_LABEL = new QLabel(LENS_STATIC);
        ZOOM_LABEL->setObjectName(QString::fromUtf8("ZOOM_LABEL"));
        ZOOM_LABEL->setGeometry(QRect(22, 17, 28, 14));
        ZOOM_LABEL->setFont(font1);
        ZOOM_LABEL->setMouseTracking(false);
        ZOOM_LABEL->setAlignment(Qt::AlignCenter);
        FOCUS_LABEL = new QLabel(LENS_STATIC);
        FOCUS_LABEL->setObjectName(QString::fromUtf8("FOCUS_LABEL"));
        FOCUS_LABEL->setGeometry(QRect(78, 17, 35, 14));
        FOCUS_LABEL->setFont(font1);
        FOCUS_LABEL->setMouseTracking(false);
        FOCUS_LABEL->setAlignment(Qt::AlignCenter);
        ZOOM_IN_BTN = new QPushButton(LENS_STATIC);
        ZOOM_IN_BTN->setObjectName(QString::fromUtf8("ZOOM_IN_BTN"));
        ZOOM_IN_BTN->setGeometry(QRect(10, 37, 21, 20));
        ZOOM_IN_BTN->setFont(font1);
        ZOOM_IN_BTN->setMouseTracking(false);
        FOCUS_NEAR_BTN = new QPushButton(LENS_STATIC);
        FOCUS_NEAR_BTN->setObjectName(QString::fromUtf8("FOCUS_NEAR_BTN"));
        FOCUS_NEAR_BTN->setGeometry(QRect(70, 37, 21, 20));
        FOCUS_NEAR_BTN->setFont(font1);
        FOCUS_NEAR_BTN->setMouseTracking(false);
        ZOOM_OUT_BTN = new QPushButton(LENS_STATIC);
        ZOOM_OUT_BTN->setObjectName(QString::fromUtf8("ZOOM_OUT_BTN"));
        ZOOM_OUT_BTN->setGeometry(QRect(40, 37, 21, 20));
        ZOOM_OUT_BTN->setFont(font1);
        ZOOM_OUT_BTN->setMouseTracking(false);
        FOCUS_FAR_BTN = new QPushButton(LENS_STATIC);
        FOCUS_FAR_BTN->setObjectName(QString::fromUtf8("FOCUS_FAR_BTN"));
        FOCUS_FAR_BTN->setGeometry(QRect(100, 37, 21, 20));
        FOCUS_FAR_BTN->setFont(font1);
        FOCUS_FAR_BTN->setMouseTracking(false);
        FOCUS_SPEED_SLIDER = new QSlider(LENS_STATIC);
        FOCUS_SPEED_SLIDER->setObjectName(QString::fromUtf8("FOCUS_SPEED_SLIDER"));
        FOCUS_SPEED_SLIDER->setGeometry(QRect(130, 30, 61, 16));
        FOCUS_SPEED_SLIDER->setFont(font1);
        FOCUS_SPEED_SLIDER->setMouseTracking(false);
        FOCUS_SPEED_SLIDER->setOrientation(Qt::Horizontal);
        FOCUS_SPEED_EDIT = new QLineEdit(LENS_STATIC);
        FOCUS_SPEED_EDIT->setObjectName(QString::fromUtf8("FOCUS_SPEED_EDIT"));
        FOCUS_SPEED_EDIT->setGeometry(QRect(195, 27, 21, 24));
        FOCUS_SPEED_EDIT->setFont(font1);
        FOCUS_SPEED_EDIT->setMouseTracking(false);
        ZOOM_EDIT = new QLineEdit(LENS_STATIC);
        ZOOM_EDIT->setObjectName(QString::fromUtf8("ZOOM_EDIT"));
        ZOOM_EDIT->setGeometry(QRect(10, 67, 51, 20));
        ZOOM_EDIT->setFont(font1);
        ZOOM_EDIT->setMouseTracking(false);
        FOCUS_EDIT = new QLineEdit(LENS_STATIC);
        FOCUS_EDIT->setObjectName(QString::fromUtf8("FOCUS_EDIT"));
        FOCUS_EDIT->setGeometry(QRect(70, 67, 51, 20));
        FOCUS_EDIT->setFont(font1);
        FOCUS_EDIT->setMouseTracking(false);
        GET_LENS_PARAM_BTN = new QPushButton(LENS_STATIC);
        GET_LENS_PARAM_BTN->setObjectName(QString::fromUtf8("GET_LENS_PARAM_BTN"));
        GET_LENS_PARAM_BTN->setGeometry(QRect(135, 67, 31, 20));
        GET_LENS_PARAM_BTN->setFont(font1);
        GET_LENS_PARAM_BTN->setMouseTracking(false);
        AUTO_FOCUS_BTN = new QPushButton(LENS_STATIC);
        AUTO_FOCUS_BTN->setObjectName(QString::fromUtf8("AUTO_FOCUS_BTN"));
        AUTO_FOCUS_BTN->setGeometry(QRect(175, 67, 31, 20));
        AUTO_FOCUS_BTN->setFont(font1);
        AUTO_FOCUS_BTN->setMouseTracking(false);
        TCU_STATIC = new QGroupBox(RIGHT);
        TCU_STATIC->setObjectName(QString::fromUtf8("TCU_STATIC"));
        TCU_STATIC->setGeometry(QRect(10, 10, 221, 241));
        TCU_STATIC->setFont(font1);
        TCU_STATIC->setMouseTracking(false);
        FREQ_EDIT = new QLineEdit(TCU_STATIC);
        FREQ_EDIT->setObjectName(QString::fromUtf8("FREQ_EDIT"));
        FREQ_EDIT->setGeometry(QRect(20, 31, 61, 20));
        FREQ_EDIT->setFont(font1);
        FREQ_EDIT->setMouseTracking(false);
        FREQ = new QLabel(TCU_STATIC);
        FREQ->setObjectName(QString::fromUtf8("FREQ"));
        FREQ->setGeometry(QRect(20, 17, 63, 14));
        FREQ->setFont(font1);
        FREQ->setMouseTracking(false);
        FREQ->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        FREQ_UNIT = new QLabel(TCU_STATIC);
        FREQ_UNIT->setObjectName(QString::fromUtf8("FREQ_UNIT"));
        FREQ_UNIT->setGeometry(QRect(84, 34, 21, 14));
        FREQ_UNIT->setFont(font1);
        FREQ_UNIT->setMouseTracking(false);
        LASER_WIDTH = new QLabel(TCU_STATIC);
        LASER_WIDTH->setObjectName(QString::fromUtf8("LASER_WIDTH"));
        LASER_WIDTH->setGeometry(QRect(110, 17, 77, 14));
        LASER_WIDTH->setFont(font1);
        LASER_WIDTH->setMouseTracking(false);
        LASER_WIDTH->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        LASER_WIDTH_EDIT_U = new QLineEdit(TCU_STATIC);
        LASER_WIDTH_EDIT_U->setObjectName(QString::fromUtf8("LASER_WIDTH_EDIT_U"));
        LASER_WIDTH_EDIT_U->setGeometry(QRect(110, 31, 31, 20));
        LASER_WIDTH_EDIT_U->setFont(font1);
        LASER_WIDTH_EDIT_U->setMouseTracking(false);
        LASER_WIDTH_EDIT_N = new QLineEdit(TCU_STATIC);
        LASER_WIDTH_EDIT_N->setObjectName(QString::fromUtf8("LASER_WIDTH_EDIT_N"));
        LASER_WIDTH_EDIT_N->setGeometry(QRect(160, 31, 31, 20));
        LASER_WIDTH_EDIT_N->setFont(font1);
        LASER_WIDTH_EDIT_N->setMouseTracking(false);
        LASER_WIDTH_U_UNIT = new QLabel(TCU_STATIC);
        LASER_WIDTH_U_UNIT->setObjectName(QString::fromUtf8("LASER_WIDTH_U_UNIT"));
        LASER_WIDTH_U_UNIT->setGeometry(QRect(138, 34, 21, 14));
        LASER_WIDTH_U_UNIT->setFont(font1);
        LASER_WIDTH_U_UNIT->setMouseTracking(false);
        LASER_WIDTH_N_UNIT = new QLabel(TCU_STATIC);
        LASER_WIDTH_N_UNIT->setObjectName(QString::fromUtf8("LASER_WIDTH_N_UNIT"));
        LASER_WIDTH_N_UNIT->setGeometry(QRect(194, 34, 14, 14));
        LASER_WIDTH_N_UNIT->setFont(font1);
        LASER_WIDTH_N_UNIT->setMouseTracking(false);
        MCP_SLIDER = new QSlider(TCU_STATIC);
        MCP_SLIDER->setObjectName(QString::fromUtf8("MCP_SLIDER"));
        MCP_SLIDER->setGeometry(QRect(20, 70, 121, 16));
        MCP_SLIDER->setFont(font1);
        MCP_SLIDER->setMouseTracking(false);
        MCP_SLIDER->setOrientation(Qt::Horizontal);
        MCP = new QLabel(TCU_STATIC);
        MCP->setObjectName(QString::fromUtf8("MCP"));
        MCP->setGeometry(QRect(20, 57, 21, 14));
        MCP->setFont(font1);
        MCP->setMouseTracking(false);
        TCU_A = new QLabel(TCU_STATIC);
        TCU_A->setObjectName(QString::fromUtf8("TCU_A"));
        TCU_A->setGeometry(QRect(50, 91, 7, 14));
        TCU_A->setFont(font1);
        TCU_A->setMouseTracking(false);
        TCU_B = new QLabel(TCU_STATIC);
        TCU_B->setObjectName(QString::fromUtf8("TCU_B"));
        TCU_B->setGeometry(QRect(160, 91, 7, 14));
        TCU_B->setFont(font1);
        TCU_B->setMouseTracking(false);
        DELAY_A_UNIT_N = new QLabel(TCU_STATIC);
        DELAY_A_UNIT_N->setObjectName(QString::fromUtf8("DELAY_A_UNIT_N"));
        DELAY_A_UNIT_N->setGeometry(QRect(94, 123, 14, 14));
        DELAY_A_UNIT_N->setFont(font1);
        DELAY_A_UNIT_N->setMouseTracking(false);
        DELAY_A_EDIT_N = new QLineEdit(TCU_STATIC);
        DELAY_A_EDIT_N->setObjectName(QString::fromUtf8("DELAY_A_EDIT_N"));
        DELAY_A_EDIT_N->setGeometry(QRect(60, 120, 31, 20));
        DELAY_A_EDIT_N->setFont(font1);
        DELAY_A_EDIT_N->setMouseTracking(false);
        DELAY_A_UNIT_U = new QLabel(TCU_STATIC);
        DELAY_A_UNIT_U->setObjectName(QString::fromUtf8("DELAY_A_UNIT_U"));
        DELAY_A_UNIT_U->setGeometry(QRect(38, 123, 21, 14));
        DELAY_A_UNIT_U->setFont(font1);
        DELAY_A_UNIT_U->setMouseTracking(false);
        DELAY_A = new QLabel(TCU_STATIC);
        DELAY_A->setObjectName(QString::fromUtf8("DELAY_A"));
        DELAY_A->setGeometry(QRect(37, 103, 35, 14));
        DELAY_A->setFont(font1);
        DELAY_A->setMouseTracking(false);
        DELAY_A->setAlignment(Qt::AlignCenter);
        DELAY_A_EDIT_U = new QLineEdit(TCU_STATIC);
        DELAY_A_EDIT_U->setObjectName(QString::fromUtf8("DELAY_A_EDIT_U"));
        DELAY_A_EDIT_U->setGeometry(QRect(10, 120, 31, 20));
        DELAY_A_EDIT_U->setFont(font1);
        DELAY_A_EDIT_U->setMouseTracking(false);
        DELAY_B = new QLabel(TCU_STATIC);
        DELAY_B->setObjectName(QString::fromUtf8("DELAY_B"));
        DELAY_B->setGeometry(QRect(147, 103, 35, 14));
        DELAY_B->setFont(font1);
        DELAY_B->setMouseTracking(false);
        DELAY_B->setAlignment(Qt::AlignCenter);
        DELAY_B_EDIT_U = new QLineEdit(TCU_STATIC);
        DELAY_B_EDIT_U->setObjectName(QString::fromUtf8("DELAY_B_EDIT_U"));
        DELAY_B_EDIT_U->setGeometry(QRect(120, 120, 31, 20));
        DELAY_B_EDIT_U->setFont(font1);
        DELAY_B_EDIT_U->setMouseTracking(false);
        DELAY_B_UNIT_U = new QLabel(TCU_STATIC);
        DELAY_B_UNIT_U->setObjectName(QString::fromUtf8("DELAY_B_UNIT_U"));
        DELAY_B_UNIT_U->setGeometry(QRect(148, 123, 21, 14));
        DELAY_B_UNIT_U->setFont(font1);
        DELAY_B_UNIT_U->setMouseTracking(false);
        DELAY_B_UNIT_N = new QLabel(TCU_STATIC);
        DELAY_B_UNIT_N->setObjectName(QString::fromUtf8("DELAY_B_UNIT_N"));
        DELAY_B_UNIT_N->setGeometry(QRect(204, 123, 14, 14));
        DELAY_B_UNIT_N->setFont(font1);
        DELAY_B_UNIT_N->setMouseTracking(false);
        DELAY_B_EDIT_N = new QLineEdit(TCU_STATIC);
        DELAY_B_EDIT_N->setObjectName(QString::fromUtf8("DELAY_B_EDIT_N"));
        DELAY_B_EDIT_N->setGeometry(QRect(170, 120, 31, 20));
        DELAY_B_EDIT_N->setFont(font1);
        DELAY_B_EDIT_N->setMouseTracking(false);
        GATE_WIDTH_A = new QLabel(TCU_STATIC);
        GATE_WIDTH_A->setObjectName(QString::fromUtf8("GATE_WIDTH_A"));
        GATE_WIDTH_A->setGeometry(QRect(32, 183, 70, 14));
        GATE_WIDTH_A->setFont(font1);
        GATE_WIDTH_A->setMouseTracking(false);
        GATE_WIDTH_A->setAlignment(Qt::AlignCenter);
        GATE_WIDTH_A_EDIT_U = new QLineEdit(TCU_STATIC);
        GATE_WIDTH_A_EDIT_U->setObjectName(QString::fromUtf8("GATE_WIDTH_A_EDIT_U"));
        GATE_WIDTH_A_EDIT_U->setGeometry(QRect(20, 200, 31, 20));
        GATE_WIDTH_A_EDIT_U->setFont(font1);
        GATE_WIDTH_A_EDIT_U->setMouseTracking(false);
        GATE_WIDTH_A_UNIT_U = new QLabel(TCU_STATIC);
        GATE_WIDTH_A_UNIT_U->setObjectName(QString::fromUtf8("GATE_WIDTH_A_UNIT_U"));
        GATE_WIDTH_A_UNIT_U->setGeometry(QRect(48, 203, 21, 14));
        GATE_WIDTH_A_UNIT_U->setFont(font1);
        GATE_WIDTH_A_UNIT_U->setMouseTracking(false);
        STRIDE_EDIT = new QLineEdit(TCU_STATIC);
        STRIDE_EDIT->setObjectName(QString::fromUtf8("STRIDE_EDIT"));
        STRIDE_EDIT->setGeometry(QRect(140, 200, 51, 20));
        STRIDE_EDIT->setFont(font1);
        STRIDE_EDIT->setMouseTracking(false);
        GATE_WIDTH_A_UNIT_N = new QLabel(TCU_STATIC);
        GATE_WIDTH_A_UNIT_N->setObjectName(QString::fromUtf8("GATE_WIDTH_A_UNIT_N"));
        GATE_WIDTH_A_UNIT_N->setGeometry(QRect(104, 203, 14, 14));
        GATE_WIDTH_A_UNIT_N->setFont(font1);
        GATE_WIDTH_A_UNIT_N->setMouseTracking(false);
        STRIDE = new QLabel(TCU_STATIC);
        STRIDE->setObjectName(QString::fromUtf8("STRIDE"));
        STRIDE->setGeometry(QRect(132, 183, 70, 14));
        STRIDE->setFont(font1);
        STRIDE->setMouseTracking(false);
        STRIDE->setAlignment(Qt::AlignCenter);
        STRIDE_UNIT = new QLabel(TCU_STATIC);
        STRIDE_UNIT->setObjectName(QString::fromUtf8("STRIDE_UNIT"));
        STRIDE_UNIT->setGeometry(QRect(194, 203, 7, 14));
        STRIDE_UNIT->setFont(font1);
        STRIDE_UNIT->setMouseTracking(false);
        GATE_WIDTH_A_EDIT_N = new QLineEdit(TCU_STATIC);
        GATE_WIDTH_A_EDIT_N->setObjectName(QString::fromUtf8("GATE_WIDTH_A_EDIT_N"));
        GATE_WIDTH_A_EDIT_N->setGeometry(QRect(70, 200, 31, 20));
        GATE_WIDTH_A_EDIT_N->setFont(font1);
        GATE_WIDTH_A_EDIT_N->setMouseTracking(false);
        ESTIMATED = new QLabel(TCU_STATIC);
        ESTIMATED->setObjectName(QString::fromUtf8("ESTIMATED"));
        ESTIMATED->setGeometry(QRect(25, 147, 105, 14));
        ESTIMATED->setFont(font1);
        ESTIMATED->setMouseTracking(false);
        ESTIMATED->setAlignment(Qt::AlignCenter);
        EST_DIST = new QLabel(TCU_STATIC);
        EST_DIST->setObjectName(QString::fromUtf8("EST_DIST"));
        EST_DIST->setGeometry(QRect(140, 147, 61, 13));
        EST_DIST->setFont(font);
        EST_DIST->setMouseTracking(false);
        EST_DIST->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        DELAY_SLIDER = new QSlider(TCU_STATIC);
        DELAY_SLIDER->setObjectName(QString::fromUtf8("DELAY_SLIDER"));
        DELAY_SLIDER->setGeometry(QRect(30, 163, 161, 20));
        DELAY_SLIDER->setFont(font1);
        DELAY_SLIDER->setMouseTracking(false);
        DELAY_SLIDER->setOrientation(Qt::Horizontal);
        DELAY_N_EDIT_N = new QLineEdit(TCU_STATIC);
        DELAY_N_EDIT_N->setObjectName(QString::fromUtf8("DELAY_N_EDIT_N"));
        DELAY_N_EDIT_N->setGeometry(QRect(150, 71, 51, 20));
        DELAY_N_EDIT_N->setFont(font1);
        DELAY_N_EDIT_N->setMouseTracking(false);
        DELAY_N_UNIT_N = new QLabel(TCU_STATIC);
        DELAY_N_UNIT_N->setObjectName(QString::fromUtf8("DELAY_N_UNIT_N"));
        DELAY_N_UNIT_N->setGeometry(QRect(204, 74, 14, 14));
        DELAY_N_UNIT_N->setFont(font1);
        DELAY_N_UNIT_N->setMouseTracking(false);
        DELAY_N = new QLabel(TCU_STATIC);
        DELAY_N->setObjectName(QString::fromUtf8("DELAY_N"));
        DELAY_N->setGeometry(QRect(150, 57, 49, 14));
        DELAY_N->setFont(font1);
        DELAY_N->setMouseTracking(false);
        DELAY_N->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ESTIMATED_2 = new QLabel(TCU_STATIC);
        ESTIMATED_2->setObjectName(QString::fromUtf8("ESTIMATED_2"));
        ESTIMATED_2->setGeometry(QRect(35, 227, 98, 14));
        ESTIMATED_2->setFont(font1);
        ESTIMATED_2->setMouseTracking(false);
        ESTIMATED_2->setAlignment(Qt::AlignCenter);
        GATE_WIDTH = new QLabel(TCU_STATIC);
        GATE_WIDTH->setObjectName(QString::fromUtf8("GATE_WIDTH"));
        GATE_WIDTH->setGeometry(QRect(140, 227, 47, 13));
        GATE_WIDTH->setFont(font);
        GATE_WIDTH->setMouseTracking(false);
        GATE_WIDTH->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        FREQ_EDIT->raise();
        FREQ->raise();
        FREQ_UNIT->raise();
        LASER_WIDTH->raise();
        LASER_WIDTH_EDIT_N->raise();
        LASER_WIDTH_U_UNIT->raise();
        LASER_WIDTH_N_UNIT->raise();
        MCP_SLIDER->raise();
        MCP->raise();
        TCU_A->raise();
        TCU_B->raise();
        DELAY_A_UNIT_N->raise();
        DELAY_A_EDIT_N->raise();
        DELAY_A_UNIT_U->raise();
        DELAY_A->raise();
        DELAY_A_EDIT_U->raise();
        DELAY_B->raise();
        DELAY_B_UNIT_U->raise();
        DELAY_B_UNIT_N->raise();
        DELAY_B_EDIT_N->raise();
        GATE_WIDTH_A->raise();
        GATE_WIDTH_A_UNIT_U->raise();
        STRIDE_EDIT->raise();
        GATE_WIDTH_A_UNIT_N->raise();
        STRIDE->raise();
        STRIDE_UNIT->raise();
        GATE_WIDTH_A_EDIT_N->raise();
        ESTIMATED->raise();
        EST_DIST->raise();
        DELAY_SLIDER->raise();
        DELAY_N_EDIT_N->raise();
        DELAY_N_UNIT_N->raise();
        DELAY_N->raise();
        LASER_WIDTH_EDIT_U->raise();
        DELAY_B_EDIT_U->raise();
        GATE_WIDTH_A_EDIT_U->raise();
        ESTIMATED_2->raise();
        GATE_WIDTH->raise();
        OPERATION_STATIC = new QGroupBox(RIGHT);
        OPERATION_STATIC->setObjectName(QString::fromUtf8("OPERATION_STATIC"));
        OPERATION_STATIC->setGeometry(QRect(10, 460, 221, 116));
        OPERATION_STATIC->setFont(font1);
        OPERATION_STATIC->setMouseTracking(false);
        IMG_ENHANCE_CHECK = new QCheckBox(OPERATION_STATIC);
        IMG_ENHANCE_CHECK->setObjectName(QString::fromUtf8("IMG_ENHANCE_CHECK"));
        IMG_ENHANCE_CHECK->setGeometry(QRect(11, 15, 74, 20));
        IMG_ENHANCE_CHECK->setFont(font1);
        IMG_ENHANCE_CHECK->setMouseTracking(false);
        ENHANCE_OPTIONS = new QComboBox(OPERATION_STATIC);
        ENHANCE_OPTIONS->setObjectName(QString::fromUtf8("ENHANCE_OPTIONS"));
        ENHANCE_OPTIONS->setGeometry(QRect(110, 14, 101, 20));
        ENHANCE_OPTIONS->setFont(font1);
        ENHANCE_OPTIONS->setMouseTracking(false);
        SP_CHECK = new QCheckBox(OPERATION_STATIC);
        SP_CHECK->setObjectName(QString::fromUtf8("SP_CHECK"));
        SP_CHECK->setGeometry(QRect(11, 40, 39, 20));
        SP_CHECK->setFont(font1);
        SP_CHECK->setMouseTracking(false);
        SP_OPTIONS = new QComboBox(OPERATION_STATIC);
        SP_OPTIONS->setObjectName(QString::fromUtf8("SP_OPTIONS"));
        SP_OPTIONS->setGeometry(QRect(52, 39, 51, 20));
        SP_OPTIONS->setFont(font1);
        SP_OPTIONS->setMouseTracking(false);
        FRAME_AVG_CHECK = new QCheckBox(OPERATION_STATIC);
        FRAME_AVG_CHECK->setObjectName(QString::fromUtf8("FRAME_AVG_CHECK"));
        FRAME_AVG_CHECK->setGeometry(QRect(11, 65, 46, 20));
        FRAME_AVG_CHECK->setFont(font1);
        FRAME_AVG_CHECK->setMouseTracking(false);
        FRAME_AVG_OPTIONS = new QComboBox(OPERATION_STATIC);
        FRAME_AVG_OPTIONS->setObjectName(QString::fromUtf8("FRAME_AVG_OPTIONS"));
        FRAME_AVG_OPTIONS->setGeometry(QRect(52, 64, 51, 20));
        FRAME_AVG_OPTIONS->setFont(font1);
        FRAME_AVG_OPTIONS->setMouseTracking(false);
        IMG_3D_CHECK = new QCheckBox(OPERATION_STATIC);
        IMG_3D_CHECK->setObjectName(QString::fromUtf8("IMG_3D_CHECK"));
        IMG_3D_CHECK->setGeometry(QRect(11, 90, 39, 20));
        IMG_3D_CHECK->setFont(font1);
        IMG_3D_CHECK->setMouseTracking(false);
        RANGE_THRESH_EDIT = new QLineEdit(OPERATION_STATIC);
        RANGE_THRESH_EDIT->setObjectName(QString::fromUtf8("RANGE_THRESH_EDIT"));
        RANGE_THRESH_EDIT->setGeometry(QRect(52, 89, 51, 20));
        RANGE_THRESH_EDIT->setFont(font1);
        RANGE_THRESH_EDIT->setMouseTracking(false);
        RANGE_THRESH_EDIT->setLayoutDirection(Qt::LeftToRight);
        RANGE_THRESH_EDIT->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CONTRAST_SLIDER = new QSlider(OPERATION_STATIC);
        CONTRAST_SLIDER->setObjectName(QString::fromUtf8("CONTRAST_SLIDER"));
        CONTRAST_SLIDER->setGeometry(QRect(120, 95, 80, 12));
        CONTRAST_SLIDER->setFont(font1);
        CONTRAST_SLIDER->setMouseTracking(false);
        CONTRAST_SLIDER->setSliderPosition(0);
        CONTRAST_SLIDER->setOrientation(Qt::Horizontal);
        CONTRAST_SLIDER->setTickPosition(QSlider::NoTicks);
        CONTRAST_SLIDER->setTickInterval(5);
        BRIGHTNESS_SLIDER = new QSlider(OPERATION_STATIC);
        BRIGHTNESS_SLIDER->setObjectName(QString::fromUtf8("BRIGHTNESS_SLIDER"));
        BRIGHTNESS_SLIDER->setGeometry(QRect(120, 60, 80, 12));
        BRIGHTNESS_SLIDER->setFont(font1);
        BRIGHTNESS_SLIDER->setMouseTracking(false);
        BRIGHTNESS_SLIDER->setSliderPosition(0);
        BRIGHTNESS_SLIDER->setOrientation(Qt::Horizontal);
        BRIGHTNESS_SLIDER->setTickPosition(QSlider::NoTicks);
        BRIGHTNESS_SLIDER->setTickInterval(5);
        BRIGHTNESS_LABEL = new QLabel(OPERATION_STATIC);
        BRIGHTNESS_LABEL->setObjectName(QString::fromUtf8("BRIGHTNESS_LABEL"));
        BRIGHTNESS_LABEL->setGeometry(QRect(125, 45, 70, 14));
        BRIGHTNESS_LABEL->setFont(font1);
        BRIGHTNESS_LABEL->setMouseTracking(false);
        BRIGHTNESS_LABEL->setAlignment(Qt::AlignCenter);
        CONTRAST_LABEL = new QLabel(OPERATION_STATIC);
        CONTRAST_LABEL->setObjectName(QString::fromUtf8("CONTRAST_LABEL"));
        CONTRAST_LABEL->setGeometry(QRect(132, 80, 56, 14));
        CONTRAST_LABEL->setFont(font1);
        CONTRAST_LABEL->setMouseTracking(false);
        CONTRAST_LABEL->setAlignment(Qt::AlignCenter);
        RESTART_SCAN_BUTTON = new QPushButton(RIGHT);
        RESTART_SCAN_BUTTON->setObjectName(QString::fromUtf8("RESTART_SCAN_BUTTON"));
        RESTART_SCAN_BUTTON->setGeometry(QRect(130, 600, 80, 21));
        RESTART_SCAN_BUTTON->setFont(font1);
        RESTART_SCAN_BUTTON->setMouseTracking(false);
        CONTINUE_SCAN_BUTTON = new QPushButton(RIGHT);
        CONTINUE_SCAN_BUTTON->setObjectName(QString::fromUtf8("CONTINUE_SCAN_BUTTON"));
        CONTINUE_SCAN_BUTTON->setGeometry(QRect(130, 580, 80, 21));
        CONTINUE_SCAN_BUTTON->setFont(font1);
        CONTINUE_SCAN_BUTTON->setMouseTracking(false);
        SCAN_BUTTON = new QPushButton(RIGHT);
        SCAN_BUTTON->setObjectName(QString::fromUtf8("SCAN_BUTTON"));
        SCAN_BUTTON->setGeometry(QRect(30, 580, 51, 21));
        SCAN_BUTTON->setFont(font1);
        SCAN_BUTTON->setMouseTracking(false);
        IMG_SAVE_STATIC = new QGroupBox(RIGHT);
        IMG_SAVE_STATIC->setObjectName(QString::fromUtf8("IMG_SAVE_STATIC"));
        IMG_SAVE_STATIC->setGeometry(QRect(10, 365, 221, 86));
        IMG_SAVE_STATIC->setFont(font1);
        IMG_SAVE_STATIC->setMouseTracking(false);
        SAVE_BMP_BUTTON = new QPushButton(IMG_SAVE_STATIC);
        SAVE_BMP_BUTTON->setObjectName(QString::fromUtf8("SAVE_BMP_BUTTON"));
        SAVE_BMP_BUTTON->setGeometry(QRect(20, 55, 40, 20));
        SAVE_BMP_BUTTON->setFont(font1);
        SAVE_BMP_BUTTON->setMouseTracking(false);
        FILE_PATH_EDIT = new QLineEdit(IMG_SAVE_STATIC);
        FILE_PATH_EDIT->setObjectName(QString::fromUtf8("FILE_PATH_EDIT"));
        FILE_PATH_EDIT->setGeometry(QRect(20, 15, 161, 20));
        FILE_PATH_EDIT->setFont(font1);
        FILE_PATH_EDIT->setMouseTracking(false);
        FILE_PATH_BROWSE = new QToolButton(IMG_SAVE_STATIC);
        FILE_PATH_BROWSE->setObjectName(QString::fromUtf8("FILE_PATH_BROWSE"));
        FILE_PATH_BROWSE->setGeometry(QRect(180, 15, 20, 20));
        FILE_PATH_BROWSE->setFont(font1);
        FILE_PATH_BROWSE->setMouseTracking(false);
        SAVE_AVI_BUTTON = new QPushButton(IMG_SAVE_STATIC);
        SAVE_AVI_BUTTON->setObjectName(QString::fromUtf8("SAVE_AVI_BUTTON"));
        SAVE_AVI_BUTTON->setGeometry(QRect(120, 55, 40, 20));
        SAVE_AVI_BUTTON->setFont(font1);
        SAVE_AVI_BUTTON->setMouseTracking(false);
        SAVE_FINAL_BUTTON = new QPushButton(IMG_SAVE_STATIC);
        SAVE_FINAL_BUTTON->setObjectName(QString::fromUtf8("SAVE_FINAL_BUTTON"));
        SAVE_FINAL_BUTTON->setGeometry(QRect(160, 55, 40, 20));
        SAVE_FINAL_BUTTON->setFont(font1);
        SAVE_FINAL_BUTTON->setMouseTracking(false);
        SAVE_RESULT_BUTTON = new QPushButton(IMG_SAVE_STATIC);
        SAVE_RESULT_BUTTON->setObjectName(QString::fromUtf8("SAVE_RESULT_BUTTON"));
        SAVE_RESULT_BUTTON->setGeometry(QRect(60, 55, 40, 20));
        SAVE_RESULT_BUTTON->setFont(font1);
        SAVE_RESULT_BUTTON->setMouseTracking(false);
        CAPTURE_LABEL = new QLabel(IMG_SAVE_STATIC);
        CAPTURE_LABEL->setObjectName(QString::fromUtf8("CAPTURE_LABEL"));
        CAPTURE_LABEL->setGeometry(QRect(35, 40, 49, 14));
        CAPTURE_LABEL->setFont(font1);
        CAPTURE_LABEL->setMouseTracking(false);
        CAPTURE_LABEL->setAlignment(Qt::AlignCenter);
        RECORD_LABEL = new QLabel(IMG_SAVE_STATIC);
        RECORD_LABEL->setObjectName(QString::fromUtf8("RECORD_LABEL"));
        RECORD_LABEL->setGeometry(QRect(139, 40, 42, 14));
        RECORD_LABEL->setFont(font1);
        RECORD_LABEL->setMouseTracking(false);
        RECORD_LABEL->setAlignment(Qt::AlignCenter);
        HIDE_BTN = new QPushButton(CENTRAL);
        HIDE_BTN->setObjectName(QString::fromUtf8("HIDE_BTN"));
        HIDE_BTN->setGeometry(QRect(212, 312, 16, 16));
        HIDE_BTN->setFont(font);
        HIDE_BTN->setMouseTracking(false);
        HIDE_BTN->setStyleSheet(QString::fromUtf8(""));
        TITLE = new TitleBar(CENTRAL);
        TITLE->setObjectName(QString::fromUtf8("TITLE"));
        TITLE->setGeometry(QRect(0, 0, 1130, 30));
        TITLE->setFont(font1);
        TITLE->setMouseTracking(false);
        TITLE->setFrameShape(QFrame::NoFrame);
        TITLE->setFrameShadow(QFrame::Plain);
        Demo->setCentralWidget(CENTRAL);
        RIGHT->raise();
        MID->raise();
        LEFT->raise();
        TITLE->raise();
        HIDE_BTN->raise();
        QWidget::setTabOrder(START_BUTTON, START_GRABBING_BUTTON);
        QWidget::setTabOrder(START_GRABBING_BUTTON, CCD_FREQ_EDIT);
        QWidget::setTabOrder(CCD_FREQ_EDIT, DUTY_EDIT);
        QWidget::setTabOrder(DUTY_EDIT, GAIN_EDIT);
        QWidget::setTabOrder(GAIN_EDIT, FREQ_EDIT);
        QWidget::setTabOrder(FREQ_EDIT, LASER_WIDTH_EDIT_U);
        QWidget::setTabOrder(LASER_WIDTH_EDIT_U, LASER_WIDTH_EDIT_N);
        QWidget::setTabOrder(LASER_WIDTH_EDIT_N, DELAY_N_EDIT_N);
        QWidget::setTabOrder(DELAY_N_EDIT_N, DELAY_A_EDIT_U);
        QWidget::setTabOrder(DELAY_A_EDIT_U, DELAY_A_EDIT_N);
        QWidget::setTabOrder(DELAY_A_EDIT_N, DELAY_B_EDIT_U);
        QWidget::setTabOrder(DELAY_B_EDIT_U, DELAY_B_EDIT_N);
        QWidget::setTabOrder(DELAY_B_EDIT_N, DELAY_SLIDER);
        QWidget::setTabOrder(DELAY_SLIDER, MCP_SLIDER);
        QWidget::setTabOrder(MCP_SLIDER, GATE_WIDTH_A_EDIT_U);
        QWidget::setTabOrder(GATE_WIDTH_A_EDIT_U, GATE_WIDTH_A_EDIT_N);
        QWidget::setTabOrder(GATE_WIDTH_A_EDIT_N, STRIDE_EDIT);
        QWidget::setTabOrder(STRIDE_EDIT, ZOOM_EDIT);
        QWidget::setTabOrder(ZOOM_EDIT, FOCUS_EDIT);
        QWidget::setTabOrder(FOCUS_EDIT, FOCUS_SPEED_EDIT);
        QWidget::setTabOrder(FOCUS_SPEED_EDIT, FRAME_AVG_CHECK);
        QWidget::setTabOrder(FRAME_AVG_CHECK, FRAME_AVG_OPTIONS);
        QWidget::setTabOrder(FRAME_AVG_OPTIONS, IMG_3D_CHECK);
        QWidget::setTabOrder(IMG_3D_CHECK, RANGE_THRESH_EDIT);
        QWidget::setTabOrder(RANGE_THRESH_EDIT, CONTRAST_SLIDER);
        QWidget::setTabOrder(CONTRAST_SLIDER, BRIGHTNESS_SLIDER);
        QWidget::setTabOrder(BRIGHTNESS_SLIDER, INITIALIZATION);
        QWidget::setTabOrder(INITIALIZATION, SHUTDOWN_BUTTON);
        QWidget::setTabOrder(SHUTDOWN_BUTTON, ENUM_BUTTON);
        QWidget::setTabOrder(ENUM_BUTTON, STOP_GRABBING_BUTTON);
        QWidget::setTabOrder(STOP_GRABBING_BUTTON, TCU_COM_EDIT);
        QWidget::setTabOrder(TCU_COM_EDIT, RANGE_COM_EDIT);
        QWidget::setTabOrder(RANGE_COM_EDIT, FOCUS_COM_EDIT);
        QWidget::setTabOrder(FOCUS_COM_EDIT, LASER_COM_EDIT);
        QWidget::setTabOrder(LASER_COM_EDIT, TRIGGER_RADIO);
        QWidget::setTabOrder(TRIGGER_RADIO, SAVE_BMP_BUTTON);
        QWidget::setTabOrder(SAVE_BMP_BUTTON, FILE_PATH_EDIT);
        QWidget::setTabOrder(FILE_PATH_EDIT, SET_PARAMS_BUTTON);
        QWidget::setTabOrder(SET_PARAMS_BUTTON, SAVE_FINAL_BUTTON);
        QWidget::setTabOrder(SAVE_FINAL_BUTTON, SAVE_AVI_BUTTON);
        QWidget::setTabOrder(SAVE_AVI_BUTTON, SAVE_RESULT_BUTTON);
        QWidget::setTabOrder(SAVE_RESULT_BUTTON, ENHANCE_OPTIONS);
        QWidget::setTabOrder(ENHANCE_OPTIONS, SOFTWARE_TRIGGER_BUTTON);
        QWidget::setTabOrder(SOFTWARE_TRIGGER_BUTTON, GET_PARAMS_BUTTON);
        QWidget::setTabOrder(GET_PARAMS_BUTTON, IMG_ENHANCE_CHECK);
        QWidget::setTabOrder(IMG_ENHANCE_CHECK, SOFTWARE_CHECK);
        QWidget::setTabOrder(SOFTWARE_CHECK, GAIN_SLIDER);
        QWidget::setTabOrder(GAIN_SLIDER, FILE_PATH_BROWSE);
        QWidget::setTabOrder(FILE_PATH_BROWSE, ZOOM_IN_BTN);
        QWidget::setTabOrder(ZOOM_IN_BTN, FOCUS_NEAR_BTN);
        QWidget::setTabOrder(FOCUS_NEAR_BTN, ZOOM_OUT_BTN);
        QWidget::setTabOrder(ZOOM_OUT_BTN, FOCUS_FAR_BTN);
        QWidget::setTabOrder(FOCUS_FAR_BTN, FOCUS_SPEED_SLIDER);
        QWidget::setTabOrder(FOCUS_SPEED_SLIDER, SP_OPTIONS);
        QWidget::setTabOrder(SP_OPTIONS, CONTINUOUS_RADIO);
        QWidget::setTabOrder(CONTINUOUS_RADIO, SP_CHECK);
        QWidget::setTabOrder(SP_CHECK, GET_LENS_PARAM_BTN);
        QWidget::setTabOrder(GET_LENS_PARAM_BTN, AUTO_FOCUS_BTN);
        QWidget::setTabOrder(AUTO_FOCUS_BTN, DATA_EXCHANGE);
        QWidget::setTabOrder(DATA_EXCHANGE, DIST_BTN);
        QWidget::setTabOrder(DIST_BTN, SCAN_BUTTON);
        QWidget::setTabOrder(SCAN_BUTTON, CONTINUE_SCAN_BUTTON);
        QWidget::setTabOrder(CONTINUE_SCAN_BUTTON, RESTART_SCAN_BUTTON);
        QWidget::setTabOrder(RESTART_SCAN_BUTTON, CURRENT_EDIT);
        QWidget::setTabOrder(CURRENT_EDIT, LASER_ZOOM_IN_BTN);
        QWidget::setTabOrder(LASER_ZOOM_IN_BTN, LASER_ZOOM_OUT_BTN);
        QWidget::setTabOrder(LASER_ZOOM_OUT_BTN, LASER_BTN);
        QWidget::setTabOrder(LASER_BTN, CENTER_CHECK);

        retranslateUi(Demo);

        INITIALIZATION->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Demo);
    } // setupUi

    void retranslateUi(QMainWindow *Demo)
    {
        Demo->setWindowTitle(QApplication::translate("Demo", " YJS", nullptr));
        ACTION_IMPORT->setText(QApplication::translate("Demo", "Import", nullptr));
        ACTION_EXPORT->setText(QApplication::translate("Demo", "Export", nullptr));
        ACTION_DEVICES->setText(QApplication::translate("Demo", "Devices", nullptr));
        ACTION_SERIAL_PORTS->setText(QApplication::translate("Demo", "Serial Ports", nullptr));
        PARAMS_STATIC->setTitle(QApplication::translate("Demo", "Parameters", nullptr));
        GAIN_STATIC->setText(QApplication::translate("Demo", "Gain", nullptr));
        GAIN_EDIT->setText(QApplication::translate("Demo", "0", nullptr));
        SET_PARAMS_BUTTON->setText(QApplication::translate("Demo", "Set params", nullptr));
        GET_PARAMS_BUTTON->setText(QApplication::translate("Demo", "Get params", nullptr));
        DUTY_EDIT->setText(QApplication::translate("Demo", "5", nullptr));
        CCD_FREQ_EDIT->setText(QApplication::translate("Demo", "10", nullptr));
        DUTY_UNIT->setText(QApplication::translate("Demo", "ms", nullptr));
        DUTY->setText(QApplication::translate("Demo", "Time Expo.", nullptr));
        CCD_FREQ->setText(QApplication::translate("Demo", "CCD Freq", nullptr));
        CCD_FREQ_UNIT->setText(QApplication::translate("Demo", "Hz", nullptr));
        IMG_GRAB_STATIC->setTitle(QApplication::translate("Demo", "Img aquisition", nullptr));
        CONTINUOUS_RADIO->setText(QApplication::translate("Demo", "Continuous", nullptr));
        TRIGGER_RADIO->setText(QApplication::translate("Demo", "Trigger", nullptr));
        SOFTWARE_CHECK->setText(QApplication::translate("Demo", "By software", nullptr));
        START_GRABBING_BUTTON->setText(QApplication::translate("Demo", "Start", nullptr));
        STOP_GRABBING_BUTTON->setText(QApplication::translate("Demo", "Stop", nullptr));
        SOFTWARE_TRIGGER_BUTTON->setText(QApplication::translate("Demo", "Grab", nullptr));
        SHUTDOWN_BUTTON->setText(QApplication::translate("Demo", "Turn off", nullptr));
        START_BUTTON->setText(QApplication::translate("Demo", "Turn on", nullptr));
        ENUM_BUTTON->setText(QApplication::translate("Demo", "Search for devices", nullptr));
        INITIALIZATION->setTabText(INITIALIZATION->indexOf(DEVICE), QApplication::translate("Demo", "devices", nullptr));
        TCU_COM->setText(QApplication::translate("Demo", "TCU", nullptr));
        RANGE_COM->setText(QApplication::translate("Demo", "RANGE", nullptr));
        FOCUS_COM->setText(QApplication::translate("Demo", "FOCUS", nullptr));
        LASER_COM->setText(QApplication::translate("Demo", "LASER", nullptr));
        TCU_COM_EDIT->setText(QApplication::translate("Demo", "3", nullptr));
        RANGE_COM_EDIT->setText(QApplication::translate("Demo", "0", nullptr));
        FOCUS_COM_EDIT->setText(QApplication::translate("Demo", "8", nullptr));
        LASER_COM_EDIT->setText(QApplication::translate("Demo", "0", nullptr));
        INITIALIZATION->setTabText(INITIALIZATION->indexOf(COM), QApplication::translate("Demo", "COMs", nullptr));
        LASER_STATIC->setTitle(QApplication::translate("Demo", "Laser", nullptr));
        CURRENT_EDIT->setText(QApplication::translate("Demo", "18", nullptr));
        LASER_ZOOM_IN_BTN->setText(QApplication::translate("Demo", "+", nullptr));
        LASER_ZOOM_LABEL->setText(QApplication::translate("Demo", "Zoom", nullptr));
        LASER_ZOOM_OUT_BTN->setText(QApplication::translate("Demo", "-", nullptr));
        LASER_BTN->setText(QApplication::translate("Demo", "ON", nullptr));
        DISTANCE->setText(QString());
        DIST_BTN->setText(QApplication::translate("Demo", "Distance", nullptr));
        COM_DATA_RADIO->setText(QApplication::translate("Demo", "data", nullptr));
        HISTOGRAM_RADIO->setText(QApplication::translate("Demo", "hist", nullptr));
        HIST_DISPLAY->setText(QString());
        ROI_RADIO->setText(QApplication::translate("Demo", "ROI", nullptr));
        CTRL_STATIC->setTitle(QApplication::translate("Demo", "GroupBox", nullptr));
        LOGO1->setText(QApplication::translate("Demo", "TextLabel", nullptr));
        NAME->setText(QApplication::translate("Demo", "TextLabel", nullptr));
        LOGO2->setText(QApplication::translate("Demo", "TextLabel", nullptr));
        SOURCE_DISPLAY->setText(QString());
        CENTER_CHECK->setText(QApplication::translate("Demo", "center", nullptr));
        RULER_H->setText(QString());
        RULER_V->setText(QString());
        DRAG_TOOL->setText(QString());
        SELECT_TOOL->setText(QString());
        INFO_CHECK->setText(QApplication::translate("Demo", "info", nullptr));
        LENS_STATIC->setTitle(QApplication::translate("Demo", "Lens", nullptr));
        ZOOM_LABEL->setText(QApplication::translate("Demo", "Zoom", nullptr));
        FOCUS_LABEL->setText(QApplication::translate("Demo", "Focus", nullptr));
        ZOOM_IN_BTN->setText(QApplication::translate("Demo", "+", nullptr));
        FOCUS_NEAR_BTN->setText(QApplication::translate("Demo", "+", nullptr));
        ZOOM_OUT_BTN->setText(QApplication::translate("Demo", "-", nullptr));
        FOCUS_FAR_BTN->setText(QApplication::translate("Demo", "-", nullptr));
        FOCUS_SPEED_EDIT->setText(QApplication::translate("Demo", "5", nullptr));
        GET_LENS_PARAM_BTN->setText(QApplication::translate("Demo", "get", nullptr));
        AUTO_FOCUS_BTN->setText(QApplication::translate("Demo", "auto", nullptr));
        TCU_STATIC->setTitle(QApplication::translate("Demo", "TCU", nullptr));
        FREQ->setText(QApplication::translate("Demo", "Frequency", nullptr));
        FREQ_UNIT->setText(QApplication::translate("Demo", "kHz", nullptr));
        LASER_WIDTH->setText(QApplication::translate("Demo", "Laser Width", nullptr));
        LASER_WIDTH_U_UNIT->setText(QApplication::translate("Demo", " \316\274s", nullptr));
        LASER_WIDTH_N_UNIT->setText(QApplication::translate("Demo", "ns", nullptr));
        MCP->setText(QApplication::translate("Demo", "MCP", nullptr));
        TCU_A->setText(QApplication::translate("Demo", "A", nullptr));
        TCU_B->setText(QApplication::translate("Demo", "B", nullptr));
        DELAY_A_UNIT_N->setText(QApplication::translate("Demo", "ns", nullptr));
        DELAY_A_UNIT_U->setText(QApplication::translate("Demo", " \316\274s", nullptr));
        DELAY_A->setText(QApplication::translate("Demo", "Delay", nullptr));
        DELAY_B->setText(QApplication::translate("Demo", "Delay", nullptr));
        DELAY_B_UNIT_U->setText(QApplication::translate("Demo", " \316\274s", nullptr));
        DELAY_B_UNIT_N->setText(QApplication::translate("Demo", "ns", nullptr));
        GATE_WIDTH_A->setText(QApplication::translate("Demo", "Gate Width", nullptr));
        GATE_WIDTH_A_UNIT_U->setText(QApplication::translate("Demo", " \316\274s", nullptr));
        GATE_WIDTH_A_UNIT_N->setText(QApplication::translate("Demo", "ns", nullptr));
        STRIDE->setText(QApplication::translate("Demo", "Stride", nullptr));
        STRIDE_UNIT->setText(QApplication::translate("Demo", "m", nullptr));
        ESTIMATED->setText(QApplication::translate("Demo", "Estimated dist.", nullptr));
        EST_DIST->setText(QString());
        DELAY_N_UNIT_N->setText(QApplication::translate("Demo", "ns", nullptr));
        DELAY_N->setText(QApplication::translate("Demo", "Delay-N", nullptr));
        ESTIMATED_2->setText(QApplication::translate("Demo", "Depth of field", nullptr));
        GATE_WIDTH->setText(QString());
        OPERATION_STATIC->setTitle(QApplication::translate("Demo", "Operations", nullptr));
        IMG_ENHANCE_CHECK->setText(QApplication::translate("Demo", "Enhance", nullptr));
        SP_CHECK->setText(QApplication::translate("Demo", "SP", nullptr));
        FRAME_AVG_CHECK->setText(QApplication::translate("Demo", "Avg", nullptr));
        IMG_3D_CHECK->setText(QApplication::translate("Demo", "3D", nullptr));
        RANGE_THRESH_EDIT->setText(QApplication::translate("Demo", "0.00", nullptr));
        BRIGHTNESS_LABEL->setText(QApplication::translate("Demo", "Brightness", nullptr));
        CONTRAST_LABEL->setText(QApplication::translate("Demo", "Contrast", nullptr));
        RESTART_SCAN_BUTTON->setText(QApplication::translate("Demo", "Restart", nullptr));
        CONTINUE_SCAN_BUTTON->setText(QApplication::translate("Demo", "Continue", nullptr));
        SCAN_BUTTON->setText(QApplication::translate("Demo", "Scan", nullptr));
        IMG_SAVE_STATIC->setTitle(QApplication::translate("Demo", "Save options", nullptr));
        SAVE_BMP_BUTTON->setText(QApplication::translate("Demo", "ORI", nullptr));
        FILE_PATH_BROWSE->setText(QApplication::translate("Demo", "...", nullptr));
        SAVE_AVI_BUTTON->setText(QApplication::translate("Demo", "ORI", nullptr));
        SAVE_FINAL_BUTTON->setText(QApplication::translate("Demo", "RES", nullptr));
        SAVE_RESULT_BUTTON->setText(QApplication::translate("Demo", "RES", nullptr));
        CAPTURE_LABEL->setText(QApplication::translate("Demo", "Capture", nullptr));
        RECORD_LABEL->setText(QApplication::translate("Demo", "Record", nullptr));
        HIDE_BTN->setText(QApplication::translate("Demo", "<<", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Demo: public Ui_Demo {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DEMO_DEV_H
